Map<String, String> ca = {
  "AF": "Afganistan",
  "AX": "Illes Aland",
  "AL": "Albània",
  "DZ": "Algèria",
  "AS": "Samoa Americana",
  "AD": "Andorra",
  "AO": "Angola",
  "AI": "Anguilla",
  "AG": "Antiga i Barbuda",
  "AR": "Argentina",
  "AM": "Armènia",
  "AW": "Aruba",
  "AC": "Illa Ascencio",
  "AU": "Austràlia",
  "AT": "Àustria",
  "AZ": "Azerbaidjan",
  "BS": "Bahames",
  "BH": "Bahrain",
  "BD": "Bangla Desh",
  "BB": "Barbats",
  "BY": "Bielorússia",
  "BE": "Bèlgica",
  "BZ": "Belize",
  "BJ": "Benin",
  "BM": "Illes Bermudes",
  "BT": "Bhutan",
  "BO": "Bolívia",
  "BA": "Bòsnia i Hercegovina",
  "BW": "Botswana",
  "BR": "Brasil",
  "IO": "Territori Britànic de l'Oceà Índic",
  "VG": "Illes Verges Britàniques",
  "BN": "Brunei",
  "BG": "Bulgària",
  "BF": "Burkina Faso",
  "BI": "Burundi",
  "KH": "Cambodja",
  "CM": "Camerun",
  "CA": "Canadà",
  "CV": "Cap Verd",
  "BQ": "Bonaire, Sant Eustaqui i Saba",
  "KY": "Illes Caiman",
  "CF": "República Centreafricana",
  "TD": "Txad",
  "CL": "Xile",
  "CN": "Xina",
  "CX": "Illa de Nadal",
  "CC": "Illes Cocos",
  "CO": "Colòmbia",
  "KM": "Comores",
  "CD": "República Democràtica del Congo",
  "CG": "República del Congo",
  "CK": "Illes Cook",
  "CR": "Costa Rica",
  "CI": "Costa d'Ivori",
  "HR": "Croàcia",
  "CU": "Cuba",
  "CW": "Curaçao",
  "CY": "Xipre",
  "CZ": "República Txeca",
  "DK": "Dinamarca",
  "DJ": "Djibouti",
  "DM": "Dominica",
  "DO": "República Dominicana",
  "TL": "Timor Oriental",
  "EC": "Equador",
  "EG": "Egipte",
  "SV": "El Salvador",
  "GQ": "Guinea Equatorial",
  "ER": "Eritrea",
  "EE": "Estònia",
  "ET": "Etiòpia",
  "FK": "Illes Malvines",
  "FO": "Illes Faroe",
  "FJ": "Fiji",
  "FI": "Finlàndia",
  "FR": "França",
  "GF": "Guaiana Francesa",
  "PF": "Polinèsia Francès",
  "GA": "Gabon",
  "GM": "Gàmbia",
  "GE": "Geòrgia",
  "DE": "Alemanya",
  "GH": "Ghana",
  "GI": "Gibraltar",
  "GR": "Grècia",
  "GL": "Groenlàndia",
  "GD": "Granada",
  "GP": "Guadalupe",
  "GU": "Guam",
  "GT": "Guatemala",
  "GG": "Guernsey",
  "GN": "Guinea Conakry",
  "GW": "Guinea Bissau",
  "GY": "Guaiana",
  "HT": "Haití",
  "HM": "Illes Heard i McDonald",
  "HN": "Hondures",
  "HK": "Hong Kong",
  "HU": "Hongria",
  "IS": "Islàndia",
  "IN": "Índia",
  "ID": "Indonèsia",
  "IR": "Iran",
  "IQ": "Iraq",
  "IE": "Irlanda",
  "IM": "Illa de l'home",
  "IL": "Israel",
  "IT": "Itàlia",
  "JM": "Jamaica",
  "JP": "Japó",
  "JE": "Jersei",
  "JO": "Jordà",
  "KZ": "Kazakhstan",
  "KE": "Kenya",
  "KI": "Kiribati",
  "XK": "Kosovo",
  "KW": "Kuwait",
  "KG": "Kirguistan",
  "LA": "Laos",
  "LV": "Letònia",
  "LB": "Líban",
  "LS": "Lesotho",
  "LR": "Libèria",
  "LY": "Líbia",
  "LI": "Liechtenstein",
  "LT": "Lituània",
  "LU": "Luxemburg",
  "MO": "Macau",
  "MK": "Macedònia",
  "MG": "Madagascar",
  "MW": "Malawi",
  "MY": "Malàisia",
  "MV": "Maldives",
  "ML": "Mali",
  "MT": "Malta",
  "MH": "Illes Marshall",
  "MQ": "Martinica",
  "MR": "Mauritània",
  "MU": "Maurici",
  "YT": "Mayotte",
  "MX": "Mèxic",
  "FM": "Micronèsia",
  "MD": "Moldàvia",
  "MC": "Mònaco",
  "MN": "Mongòlia",
  "ME": "Montenegro",
  "MS": "Montserrat",
  "MA": "Marroc",
  "MZ": "Moçambic",
  "MM": "Myanmar [Birmània]",
  "NA": "Namíbia",
  "NR": "Nauru",
  "NP": "Nepal",
  "NL": "Països Baixos",
  "NC": "Nova Caledònia",
  "NZ": "Nova Zelanda",
  "NI": "Nicaragua",
  "NE": "Níger",
  "NG": "Nigèria",
  "NU": "Niue",
  "NF": "Illa Norfolk",
  "KP": "Corea del Nord",
  "MP": "Illes Marianes del Nord",
  "NO": "Noruega",
  "OM": "Oman",
  "PK": "Pakistan",
  "PW": "Palau",
  "PS": "Territoris palestins",
  "PA": "Panamà",
  "PG": "Papua Nova Guinea",
  "PY": "Paraguai",
  "PE": "Perú",
  "PH": "Filipines",
  "PL": "Polònia",
  "PT": "Portugal",
  "PR": "Puerto Rico",
  "QA": "Katar",
  "RE": "Reunió",
  "RO": "Romania",
  "RU": "Rússia",
  "RW": "Rwanda",
  "BL": "Sant Bartomeu",
  "SH": "Santa Elena",
  "KN": "Sant Cristòfol i Neus",
  "LC": "Santa Llúcia",
  "MF": "Sant Martí",
  "PM": "Sant Pere i Miqueló",
  "VC": "Sant Vicenç",
  "WS": "Samoa",
  "SM": "Sant Marí",
  "ST": "Sao Tomé i Príncep",
  "SA": "Aràbia Saudita",
  "SN": "Senegal",
  "RS": "Sèrbia",
  "SC": "Seychelles",
  "SL": "Serra Lleona",
  "SG": "Singapur",
  "SX": "Sint Maarten",
  "SK": "Eslovàquia",
  "SI": "Eslovènia",
  "SB": "Illes Salomó",
  "SO": "Somàlia",
  "ZA": "Sud-àfrica",
  "GS": "Geòrgia del Sud i Les Illes Sandwich del Sud",
  "KR": "Corea del Sud",
  "SS": "Sudan del Sud",
  "ES": "Espanya",
  "LK": "Sri Lanka",
  "SD": "Sudan",
  "SR": "Surinam",
  "SJ": "Svalbard i Jan Mayen",
  "SZ": "Swazilàndia",
  "SE": "Suècia",
  "CH": "Suïssa",
  "SY": "Síria",
  "TW": "Taiwan",
  "TJ": "Tadjikistan",
  "TZ": "Tanzània",
  "TH": "Tailàndia",
  "TG": "Togo",
  "TK": "Tokelau",
  "TO": "Tonga",
  "TT": "Trinitat i Tobago",
  "TN": "Tunísia",
  "TR": "Turquia",
  "TM": "Turkmenistan",
  "TC": "Illes Turques i Caicos",
  "TV": "Tuvalu",
  "VI": "Illes Verges dels EUA",
  "UG": "Uganda",
  "UA": "Ucraïna",
  "AE": "Unió dels Emirats Àrabs",
  "GB": "Regne Unit",
  "US": "Estats Units",
  "UY": "Uruguai",
  "UZ": "Uzbekistan",
  "VU": "Vanuatu",
  "VA": "Ciutat del Vaticà",
  "VE": "Veneçuela",
  "VN": "Vietnam",
  "WF": "Wallis i Futuna",
  "WW": "Mundial",
  "EH": "Sàhara Occidental",
  "YE": "Iemen",
  "ZM": "Zàmbia",
  "ZW": "Zimbabwe",
  "search": "Cerca",
};
