Map<String, String> cs = {
  "AF": "Afghánistán",
  "AX": "Alandské ostrovy",
  "AL": "Albanie",
  "DZ": "Alžírsko",
  "AS": "Americká Samoa",
  "AD": "Andorra",
  "AO": "Angola",
  "AI": "Anguilla",
  "AG": "Antigua a Barbuda",
  "AR": "Argentina",
  "AM": "Arménie",
  "AW": "Aruba",
  "AC": "Ascension Island",
  "AU": "Austrálie",
  "AT": "Rakousko",
  "AZ": "Ázerbájdžán",
  "BS": "Bahamy",
  "BH": "Bahrajn",
  "BD": "Bangladéš",
  "BB": "Barbados",
  "BY": "Bělorusko",
  "BE": "Belgie",
  "BZ": "Belize",
  "BJ": "Benin",
  "BM": "Bermudy",
  "BT": "Bhútán",
  "BO": "Bolívie",
  "BA": "Bosna a Hercegovina",
  "BW": "Botswana",
  "BR": "Brazílie",
  "IO": "Britské území v Indickém oceánu",
  "VG": "Britské Panenské ostrovy",
  "BN": "Brunej",
  "BG": "Bulharsko",
  "BF": "Burkina Faso",
  "BI": "Burundi",
  "KH": "Kambodža",
  "CM": "Kamerun",
  "CA": "Kanada",
  "CV": "Kapverdy",
  "BQ": "Karibské Nizozemí",
  "KY": "Kajmanské ostrovy",
  "CF": "Středoafrická republika",
  "TD": "Čad",
  "CL": "Chile",
  "CN": "Čína",
  "CX": "Vánoční ostrov",
  "CC": "Kokosové ostrovy",
  "CO": "Kolumbie",
  "KM": "Komory",
  "CD": "Konžská demokratická republika",
  "CG": "Konžská republika",
  "CK": "Cookovy ostrovy",
  "CR": "Kostarika",
  "CI": "Pobřeží slonoviny",
  "HR": "Chorvatsko",
  "CU": "Kuba",
  "CW": "Curaçao",
  "CY": "Kypr",
  "CZ": "Česká republika",
  "DK": "Dánsko",
  "DJ": "Džibutsko",
  "DM": "Dominika",
  "DO": "Dominikánská republika",
  "TL": "Východní Timor",
  "EC": "Ekvádor",
  "EG": "Egypt",
  "SV": "Salvador",
  "GQ": "Rovníková Guinea",
  "ER": "Eritrea",
  "EE": "Estonsko",
  "ET": "Etiopie",
  "FK": "Falklandy",
  "FO": "Faerské ostrovy",
  "FJ": "Fidži",
  "FI": "Finsko",
  "FR": "Francie",
  "GF": "Francouzská Guyana",
  "PF": "Francouzská Polynésie",
  "GA": "Gabon",
  "GM": "Gambie",
  "GE": "Gruzie",
  "DE": "Německo",
  "GH": "Ghana",
  "GI": "Gibraltar",
  "GR": "Řecko",
  "GL": "Grónsko",
  "GD": "Grenada",
  "GP": "Guadeloupe",
  "GU": "Guam",
  "GT": "Guatemala",
  "GG": "Guernsey",
  "GN": "Guinea",
  "GW": "Guinea-Bissau",
  "GY": "Guyana",
  "HT": "Haiti",
  "HM": "Heardův ostrov a McDonaldovy ostrovy",
  "HN": "Honduras",
  "HK": "Hongkong",
  "HU": "Maďarsko",
  "IS": "Island",
  "IN": "Indie",
  "ID": "Indonésie",
  "IR": "Írán",
  "IQ": "Irák",
  "IE": "Irsko",
  "IM": "Ostrov Man",
  "IL": "Izrael",
  "IT": "Itálie",
  "JM": "Jamajka",
  "JP": "Japonsko",
  "JE": "Jersey",
  "JO": "Jordánsko",
  "KZ": "Kazachstán",
  "KE": "Keňa",
  "KI": "Kiribati",
  "XK": "Kosovo",
  "KW": "Kuvajt",
  "KG": "Kyrgyzstán",
  "LA": "Laos",
  "LV": "Lotyšsko",
  "LB": "Libanon",
  "LS": "Lesotho",
  "LR": "Libérie",
  "LY": "Libye",
  "LI": "Lichtenštejnsko",
  "LT": "Litva",
  "LU": "Lucembursko",
  "MO": "Macao",
  "MK": "Makedonie",
  "MG": "Madagaskar",
  "MW": "Malawi",
  "MY": "Malajsie",
  "MV": "Maladivy",
  "ML": "Mali",
  "MT": "Malta",
  "MH": "Marshallovy ostrovy",
  "MQ": "Martinik",
  "MR": "Mauritánie",
  "MU": "Mauricius",
  "YT": "Mayotte",
  "MX": "Mexiko",
  "FM": "Mikronésie",
  "MD": "Moldavsko",
  "MC": "Monako",
  "MN": "Mongolsko",
  "ME": "Černá Hora",
  "MS": "Montserrat",
  "MA": "Maroko",
  "MZ": "Mosambik",
  "MM": "Myanmar (Barma)",
  "NA": "Namibie",
  "NR": "Nauru",
  "NP": "Nepál",
  "NL": "Nizozemsko",
  "NC": "Nová Kaledonie",
  "NZ": "Nový Zéland",
  "NI": "Nikaragua",
  "NE": "Niger",
  "NG": "Nigérie",
  "NU": "Niue",
  "NF": "Norfolk",
  "KP": "Severní Korea",
  "MP": "Severní Mariany",
  "NO": "Norsko",
  "OM": "Omán",
  "PK": "Pákistán",
  "PW": "Palau",
  "PS": "Palestinská území",
  "PA": "Panama",
  "PG": "Papua Nová Guinea",
  "PY": "Paraguay",
  "PE": "Peru",
  "PH": "Filipíny",
  "PL": "Polsko",
  "PT": "Portugalsko",
  "PR": "Portoriko",
  "QA": "Katar",
  "RE": "Réunion",
  "RO": "Rumunsko",
  "RU": "Rusko",
  "RW": "Rwanda",
  "BL": "Svatý Bartoloměj",
  "SH": "Svatá Helena",
  "KN": "Svatý Kryštof a Nevis",
  "LC": "Svatá Lucie",
  "MF": "Svatý Martin",
  "PM": "Svatý Pierre a Miquelon",
  "VC": "Svatý Vincenc a Grenadiny",
  "WS": "Samoa",
  "SM": "San Marino",
  "ST": "Svatý Tomáš a Princův ostrov",
  "SA": "Saúdská Arábie",
  "SN": "Senegal",
  "RS": "Srbsko",
  "SC": "Seychely",
  "SL": "Sierra Leone",
  "SG": "Singapur",
  "SX": "Svatý Martin (nizozemská část)",
  "SK": "Slovensko",
  "SI": "Slovinsko",
  "SB": "Šalamounovy ostrovy",
  "SO": "Somálsko",
  "ZA": "Jihoafrická republika",
  "GS": "Jižní Georgie a Jižní Sandwichovy ostrovy",
  "KR": "Jižní Korea",
  "SS": "Jižní Súdán",
  "ES": "Španělsko",
  "LK": "Srí Lanka",
  "SD": "Súdán",
  "SR": "Surinam",
  "SJ": "Špicberky a Jan Mayen",
  "SZ": "Svazijsko",
  "SE": "Švédsko",
  "CH": "Švýcarsko",
  "SY": "Sýrie",
  "TW": "Tchaj-wan",
  "TJ": "Tádžikistán",
  "TZ": "Tanzanie",
  "TH": "Thajsko",
  "TG": "Togo",
  "TK": "Tokelau",
  "TO": "Tonga",
  "TT": "Trinidad a Tobago",
  "TN": "Tunisko",
  "TR": "Turecko",
  "TM": "Turkmenistán",
  "TC": "Turks a Caicos",
  "TV": "Tuvalu",
  "VI": "Americké Panenské ostrovy",
  "UG": "Uganda",
  "UA": "Ukrajina",
  "AE": "Spojené arabské emiráty",
  "GB": "Spojené království",
  "US": "Spojené státy",
  "UY": "Uruguay",
  "UZ": "Uzbekistán",
  "VU": "Vanuatu",
  "VA": "Vatikán",
  "VE": "Venezuela",
  "VN": "Vietnam",
  "WF": "Wallis a Futuna",
  "WW": "Celosvětový",
  "EH": "Západní Sahara",
  "YE": "Jemen",
  "ZM": "Zambie",
  "ZW": "Zimbabwe",
  "search": "Hledat",
};
