Map<String, String> da = {
  "AF": "Afghanistan",
  "AX": "Ålandsøerne",
  "AL": "Albanien",
  "DZ": "Algeriet",
  "AS": "Amerikansk Samoa",
  "AD": "Andorra",
  "AO": "Angola",
  "AI": "Anguilla",
  "AG": "Antigua og Barbuda",
  "AR": "Argentina",
  "AM": "Armenien",
  "AW": "Aruba",
  "AC": "Ascensionøen",
  "AU": "Australien",
  "AT": "Østrig",
  "AZ": "Aserbajdsjan",
  "BS": "Bahamas",
  "BH": "Bahrain",
  "BD": "Bangladesh",
  "BB": "Barbados",
  "BY": "Hviderusland",
  "BE": "Belgien",
  "BZ": "Belize",
  "BJ": "Benin",
  "BM": "Bermuda",
  "BT": "Bhutan",
  "BO": "Bolivia",
  "BA": "Bosnien-Hercegovina",
  "BW": "Botswana",
  "BR": "Brasilien",
  "IO": "Det Britiske Territorium i Det Indiske Ocean",
  "VG": "De Britiske Jomfruøer",
  "BN": "Brunei",
  "BG": "Bulgarien",
  "BF": "Burkina Faso",
  "BI": "Burundi",
  "KH": "Cambodja",
  "CM": "Cameroun",
  "CA": "Canada",
  "CV": "Kap Verde",
  "BQ": "De Caribiske Nederlande",
  "KY": "Caymanøerne",
  "CF": "Centralafrikanske Republik",
  "TD": "Tchad",
  "CL": "Chile",
  "CN": "Kina",
  "CX": "Juleøen",
  "CC": "Cocosøerne",
  "CO": "Colombia",
  "KM": "Comorerne",
  "CD": "Den Demokratiske Republik Congo",
  "CG": "Congo",
  "CK": "Cookøerne",
  "CR": "Costa Rica",
  "CI": "Elfenbenskysten",
  "HR": "Kroatien",
  "CU": "Cuba",
  "CW": "Curaçao",
  "CY": "Cypern",
  "CZ": "Tjekkiet",
  "DK": "Danmark",
  "DJ": "Djibouti",
  "DM": "Dominica",
  "DO": "Den Dominikanske Republik",
  "TL": "Østtimor",
  "EC": "Ecuador",
  "EG": "Egypten",
  "SV": "El Salvador",
  "GQ": "Ækvatorialguinea",
  "ER": "Eritrea",
  "EE": "Estland",
  "ET": "Etiopien",
  "FK": "Falklandsøerne",
  "FO": "Færøerne",
  "FJ": "Fiji",
  "FI": "Finland",
  "FR": "Frankrig",
  "GF": "Fransk Guyana",
  "PF": "Fransk Polynesien",
  "GA": "Gabon",
  "GM": "Gambia",
  "GE": "Georgien",
  "DE": "Tyskland",
  "GH": "Ghana",
  "GI": "Gibraltar",
  "GR": "Grækenland",
  "GL": "Grønland",
  "GD": "Grenada",
  "GP": "Guadeloupe",
  "GU": "Guam",
  "GT": "Guatemala",
  "GG": "Guernsey",
  "GN": "Guinea",
  "GW": "Guinea-Bissau",
  "GY": "Guyana",
  "HT": "Haiti",
  "HM": "Heard Island og McDonald Islands",
  "HN": "Honduras",
  "HK": "Hong Kong",
  "HU": "Ungarn",
  "IS": "Island",
  "IN": "Indien",
  "ID": "Indonesien",
  "IR": "Iran",
  "IQ": "Irak",
  "IE": "Irland",
  "IM": "Isle of Man",
  "IL": "Israel",
  "IT": "Italien",
  "JM": "Jamaica",
  "JP": "Japan",
  "JE": "Jersey",
  "JO": "Jordan",
  "KZ": "Kasakhstan",
  "KE": "Kenya",
  "KI": "Kiribati",
  "XK": "Kosovo",
  "KW": "Kuwait",
  "KG": "Kirgisistan",
  "LA": "Laos",
  "LV": "Letland",
  "LB": "Libanon",
  "LS": "Lesotho",
  "LR": "Liberia",
  "LY": "Libyen",
  "LI": "Liechtenstein",
  "LT": "Litauen",
  "LU": "Luxembourg",
  "MO": "Macau",
  "MK": "Makedonien",
  "MG": "Madagaskar",
  "MW": "Malawi",
  "MY": "Malaysia",
  "MV": "Maldiverne",
  "ML": "Mali",
  "MT": "Malta",
  "MH": "Marshalløerne",
  "MQ": "Martinique",
  "MR": "Mauretanien",
  "MU": "Mauritius",
  "YT": "Mayotte",
  "MX": "Mexico",
  "FM": "Mikronesien",
  "MD": "Moldova",
  "MC": "Monaco",
  "MN": "Mongoliet",
  "ME": "Montenegro",
  "MS": "Montserrat",
  "MA": "Marokko",
   "MZ": "Mozambique",
  "MM": "Myanmar [Burma]",
  "NA": "Namibia",
  "NR": "Nauru",
  "NP": "Nepal",
  "NL": "Nederlandene",
  "NC": "Ny Kaledonien",
  "NZ": "New Zealand",
  "NI": "Nicaragua",
  "NE": "Niger",
  "NG": "Nigeria",
  "NU": "Niue",
  "NF": "Norfolk Island",
  "KP": "Nordkorea",
  "MP": "Nordmarianerne",
  "NO": "Norge",
  "OM": "Oman",
  "PK": "Pakistan",
  "PW": "Palau",
  "PS": "Palæstinensiske Områder",
  "PA": "Panama",
  "PG": "Papua Ny Guinea",
  "PY": "Paraguay",
  "PE": "Peru",
  "PH": "Filippinerne",
  "PL": "Polen",
  "PT": "Portugal",
  "PR": "Puerto Rico",
  "QA": "Qatar",
  "RE": "Réunion",
  "RO": "Rumænien",
  "RU": "Rusland",
  "RW": "Rwanda",
  "BL": "Saint Barthélemy",
  "SH": "Saint Helena",
  "KN": "St. Kitts",
  "LC": "St. Lucia",
  "MF": "Saint Martin",
  "PM": "Saint Pierre og Miquelon",
  "VC": "St. Vincent",
  "WS": "Samoa",
  "SM": "San Marino",
  "ST": "São Tomé og Príncipe",
  "SA": "Saudi-Arabien",
  "SN": "Senegal",
  "RS": "Serbien",
  "SC": "Seychellerne",
  "SL": "Sierra Leone",
  "SG": "Singapore",
  "SX": "Sint Maarten",
  "SK": "Slovakiet",
  "SI": "Slovenien",
  "SB": "Salomonøerne",
  "SO": "Somalia",
  "ZA": "Sydafrika",
  "GS": "Sydgeorgien og Sydsandwichøerne",
  "KR": "Sydkorea",
  "SS": "Sydsudan",
  "ES": "Spanien",
  "LK": "Sri Lanka",
  "SD": "Sudan",
  "SR": "Surinam",
  "SJ": "Svalbard og Jan Mayen",
  "SZ": "Eswatini",
  "SE": "Sverige",
  "CH": "Schweiz",
  "SY": "Syrien",
  "TW": "Taiwan",
  "TJ": "Tadsjikistan",
  "TZ": "Tanzania",
  "TH": "Thailand",
  "TG": "Togo",
  "TK": "Tokelau",
  "TO": "Tonga",
  "TT": "Trinidad og Tobago",
  "TN": "Tunesien",
  "TR": "Tyrkiet",
  "TM": "Turkmenistan",
  "TC": "Turks- og Caicosøerne",
  "TV": "Tuvalu",
  "VI": "Amerikanske Jomfruøer",
  "UG": "Uganda",
  "UA": "Ukraine",
  "AE": "De Forenede Arabiske Emirater",
  "GB": "Storbritannien",
  "US": "USA",
  "UY": "Uruguay",
  "UZ": "Usbekistan",
  "VU": "Vanuatu",
  "VA": "Vatikanstaten",
  "VE": "Venezuela",
  "VN": "Vietnam",
  "WF": "Wallis og Futuna",
  "WW": "Global",
  "EH": "Vestlige Sahara",
  "YE": "Yemen",
  "ZM": "Zambia",
  "ZW": "Zimbabwe",
  "search": "Søg",
};
