Map<String, String> fi = {
  "AF": "Afganistan",
  "AX": "Ahvenanmaa",
  "AL": "Albania",
  "DZ": "Algeria",
  "AS": "Amerikan Samoa",
  "AD": "Andorra",
  "AO": "Angola",
  "AI": "Anguilla",
  "AG": "Antigua ja Barbuda",
  "AR": "Argentiina",
  "AM": "Armenia",
  "AW": "Aruba",
  "AC": "Ascension-saari",
  "AU": "Australia",
  "AT": "Itävalta",
  "AZ": "Azerbaidžan",
  "BS": "Bahama",
  "BH": "Bahrain",
  "BD": "Bangladesh",
  "BB": "Barbados",
  "BY": "Valko-Venäjä",
  "BE": "Belgia",
  "BZ": "Belize",
  "BJ": "Benin",
  "BM": "Bermuda",
  "BT": "Bhutan",
  "BO": "Bolivia",
  "BA": "Bosnia ja Hertsegovina",
  "BW": "Botswana",
  "BR": "Brasilia",
  "IO": "Brittiläinen Intian valtameren alue",
  "VG": "Brittiläiset Neitsytsaaret",
  "BN": "Brunei",
  "BG": "Bulgaria",
  "BF": "Burkina Faso",
  "BI": "Burundi",
  "KH": "Kambodža",
  "CM": "Kamerun",
  "CA": "Kanada",
  "CV": "Kap Verde",
  "BQ": "Karibian Alankomaat",
  "KY": "Caymansaaret",
  "CF": "Keski-Afrikan tasavalta",
  "TD": "Tšad",
  "CL": "Chile",
  "CN": "Kiina",
  "CX": "Joulusaari",
  "CC": "Kookossaaret",
  "CO": "Kolumbia",
  "KM": "Komorit",
  "CD": "Kongon demokraattinen tasavalta",
  "CG": "Kongon tasavalta",
  "CK": "Cookinsaaret",
  "CR": "Costa Rica",
  "CI": "Norsunluurannikko",
  "HR": "Kroatia",
  "CU": "Kuuba",
  "CW": "Curaçao",
  "CY": "Kypros",
  "CZ": "Tšekki",
  "DK": "Tanska",
  "DJ": "Djibouti",
  "DM": "Dominica",
  "DO": "Dominikaaninen tasavalta",
  "TL": "Itä-Timor",
  "EC": "Ecuador",
  "EG": "Egypti",
  "SV": "El Salvador",
  "GQ": "Päiväntasaajan Guinea",
  "ER": "Eritrea",
  "EE": "Viro",
  "ET": "Etiopia",
  "FK": "Falklandinsaaret",
  "FO": "Färsaaret",
  "FJ": "Fidži",
  "FI": "Suomi",
  "FR": "Ranska",
  "GF": "Ranskan Guyana",
  "PF": "Ranskan Polynesia",
  "GA": "Gabon",
  "GM": "Gambia",
  "GE": "Georgia",
  "DE": "Saksa",
  "GH": "Ghana",
  "GI": "Gibraltar",
  "GR": "Kreikka",
  "GL": "Grönlanti",
  "GD": "Grenada",
  "GP": "Guadeloupe",
  "GU": "Guam",
  "GT": "Guatemala",
  "GG": "Guernsey",
  "GN": "Guinea",
  "GW": "Guinea-Bissau",
  "GY": "Guyana",
  "HT": "Haiti",
  "HM": "Heard ja McDonaldinsaaret",
  "HN": "Honduras",
  "HK": "Hongkong",
  "HU": "Unkari",
  "IS": "Islanti",
  "IN": "Intia",
  "ID": "Indonesia",
  "IR": "Iran",
  "IQ": "Irak",
  "IE": "Irlanti",
  "IM": "Mansaari",
  "IL": "Israel",
  "IT": "Italia",
  "JM": "Jamaika",
  "JP": "Japani",
  "JE": "Jersey",
  "JO": "Jordania",
  "KZ": "Kazakstan",
  "KE": "Kenia",
  "KI": "Kiribati",
  "XK": "Kosovo",
  "KW": "Kuwait",
  "KG": "Kirgisia",
  "LA": "Laos",
  "LV": "Latvia",
  "LB": "Libanon",
  "LS": "Lesotho",
  "LR": "Liberia",
  "LY": "Libya",
  "LI": "Liechtenstein",
  "LT": "Liettua",
  "LU": "Luxemburg",
  "MO": "Macao",
  "MK": "Pohjois-Makedonia",
  "MG": "Madagaskar",
  "MW": "Malawi",
  "MY": "Malesia",
  "MV": "Malediivit",
  "ML": "Mali",
  "MT": "Malta",
  "MH": "Marshallinsaaret",
  "MQ": "Martinique",
  "MR": "Mauritania",
  "MU": "Mauritius",
  "YT": "Mayotte",
  "MX": "Meksiko",
  "FM": "Mikronesia",
  "MD": "Moldova",
  "MC": "Monaco",
  "MN": "Mongolia",
  "ME": "Montenegro",
  "MS": "Montserrat",
  "MA": "Marokko",
  "MZ": "Mosambik",
  "MM": "Myanmar",
  "NA": "Namibia",
  "NR": "Nauru",
  "NP": "Nepal",
  "NL": "Alankomaat",
  "NC": "Uusi-Kaledonia",
  "NZ": "Uusi-Seelanti",
  "NI": "Nicaragua",
  "NE": "Niger",
  "NG": "Nigeria",
  "NU": "Niue",
  "NF": "Norfolkinsaari",
  "KP": "Pohjois-Korea",
  "MP": "Pohjois-Mariaanit",
  "NO": "Norja",
  "OM": "Oman",
  "PK": "Pakistan",
  "PW": "Palau",
  "PS": "Palestiinalaisalueet",
  "PA": "Panama",
  "PG": "Papua-Uusi-Guinea",
  "PY": "Paraguay",
  "PE": "Peru",
  "PH": "Filippiinit",
  "PL": "Puola",
  "PT": "Portugali",
  "PR": "Puerto Rico",
  "QA": "Qatar",
  "RE": "Réunion",
  "RO": "Romania",
  "RU": "Venäjä",
  "RW": "Ruanda",
  "BL": "Saint-Barthélemy",
  "SH": "Saint Helena",
  "KN": "Saint Kitts ja Nevis",
  "LC": "Saint Lucia",
  "MF": "Saint-Martin",
  "PM": "Saint-Pierre ja Miquelon",
  "VC": "Saint Vincent ja Grenadiinit",
  "WS": "Samoa",
  "SM": "San Marino",
  "ST": "São Tomé ja Príncipe",
  "SA": "Saudi-Arabia",
  "SN": "Senegal",
  "RS": "Serbia",
  "SC": "Seychellit",
  "SL": "Sierra Leone",
  "SG": "Singapore",
  "SX": "Sint Maarten",
  "SK": "Slovakia",
  "SI": "Slovenia",
  "SB": "Salomonsaaret",
  "SO": "Somalia",
  "ZA": "Etelä-Afrikka",
  "GS": "Etelä-Georgia ja Eteläiset Sandwichsaaret",
  "KR": "Etelä-Korea",
  "SS": "Etelä-Sudan",
  "ES": "Espanja",
  "LK": "Sri Lanka",
  "SD": "Sudan",
  "SR": "Suriname",
  "SJ": "Huippuvuoret ja Jan Mayen",
  "SZ": "Eswatini",
  "SE": "Ruotsi",
  "CH": "Sveitsi",
  "SY": "Syyria",
  "TW": "Taiwan",
  "TJ": "Tadžikistan",
  "TZ": "Tansania",
  "TH": "Thaimaa",
  "TG": "Togo",
  "TK": "Tokelau",
  "TO": "Tonga",
  "TT": "Trinidad ja Tobago",
  "TN": "Tunisia",
  "TR": "Turkki",
  "TM": "Turkmenistan",
  "TC": "Turks- ja Caicossaaret",
  "TV": "Tuvalu",
  "VI": "Yhdysvaltain Neitsytsaaret",
  "UG": "Uganda",
  "UA": "Ukraina",
  "AE": "Yhdistyneet arabiemiirikunnat",
  "GB": "Yhdistynyt kuningaskunta",
  "US": "Yhdysvallat",
  "UY": "Uruguay",
  "UZ": "Uzbekistan",
  "VU": "Vanuatu",
  "VA": "Vatikaani",
  "VE": "Venezuela",
  "VN": "Vietnam",
  "WF": "Wallis ja Futuna",
  "WW": "Maailmanlaajuinen",
  "EH": "Länsi-Sahara",
  "YE": "Jemen",
  "ZM": "Sambia",
  "ZW": "Zimbabwe",
  "search": "Hae",
};
