Map<String, String> hr = {
  "AF": "Afganistan",
  "AX": "Ålandski otoci",
  "AL": "Albanija",
  "DZ": "Alžir",
  "AS": "Američka Samoa",
  "AD": "Andora",
  "AO": "Angola",
  "AI": "Angvila",
  "AG": "Antigva i Barbuda",
  "AR": "Argentina",
  "AM": "Armenija",
  "AW": "Aruba",
  "AC": "Otok Ascension",
  "AU": "Australija",
  "AT": "Austrija",
  "AZ": "Azerbajdžan",
  "BS": "Bahami",
  "BH": "Bahrein",
  "BD": "Bangladeš",
  "BB": "Barbados",
  "BY": "Bjelorusija",
  "BE": "Belgija",
  "BZ": "Belize",
  "BJ": "Benin",
  "BM": "Bermudi",
  "BT": "Butan",
  "BO": "Bolivija",
  "BA": "Bosna i Hercegovina",
  "BW": "Bocvana",
  "BR": "Brazil",
  "IO": "Britanski Indijskooceanski teritorij",
  "VG": "Britanski Djevičanski otoci",
  "BN": "Brunej",
  "BG": "Bugarska",
  "BF": "Burkina Faso",
  "BI": "Burundi",
  "KH": "Kambodža",
  "CM": "Kamerun",
  "CA": "Kanada",
  "CV": "Zelenortska Republika",
  "BQ": "Karipska Nizozemska",
  "KY": "Kajmanski otoci",
  "CF": "Srednjoafrička Republika",
  "TD": "Čad",
  "CL": "Čile",
  "CN": "Kina",
  "CX": "Božićni Otok",
  "CC": "Kokosovi otoci",
  "CO": "Kolumbija",
  "KM": "Komori",
  "CD": "Demokratska Republika Kongo",
  "CG": "Republika Kongo",
  "CK": "Cookovo Otočje",
  "CR": "Kostarika",
  "CI": "Obala Bjelokosti",
  "HR": "Hrvatska",
  "CU": "Kuba",
  "CW": "Curaçao",
  "CY": "Cipar",
  "CZ": "Češka",
  "DK": "Danska",
  "DJ": "Džibuti",
  "DM": "Dominika",
  "DO": "Dominikanska Republika",
  "TL": "Istočni Timor",
  "EC": "Ekvador",
  "EG": "Egipat",
  "SV": "Salvador",
  "GQ": "Ekvatorska Gvineja",
  "ER": "Eritreja",
  "EE": "Estonija",
  "ET": "Etiopija",
  "FK": "Falklandski otoci",
  "FO": "Føroyar",
  "FJ": "Fidži",
  "FI": "Finska",
  "FR": "Francuska",
  "GF": "Francuska Gijana",
  "PF": "Francuska Polinezija",
  "GA": "Gabon",
  "GM": "Gambija",
  "GE": "Gruzija",
  "DE": "Njemačka",
  "GH": "Gana",
  "GI": "Gibraltar",
  "GR": "Grčka",
  "GL": "Grenland",
  "GD": "Grenada",
  "GP": "Gvadalupa",
  "GU": "Guam",
  "GT": "Gvatemala",
  "GG": "Guernsey",
  "GN": "Gvineja",
  "GW": "Gvineja Bisau",
  "GY": "Gvajana",
  "HT": "Haiti",
  "HM": "Otok Heard i otočje McDonald",
  "HN": "Honduras",
  "HK": "Hong Kong",
  "HU": "Mađarska",
  "IS": "Island",
  "IN": "Indija",
  "ID": "Indonezija",
  "IR": "Iran",
  "IQ": "Irak",
  "IE": "Irska",
  "IM": "Otok Man",
  "IL": "Izrael",
  "IT": "Italija",
  "JM": "Jamajka",
  "JP": "Japan",
  "JE": "Jersey (otok)",
  "JO": "Jordan",
  "KZ": "Kazahstan",
  "KE": "Kenija",
  "KI": "Kiribati",
  "XK": "Kosovo",
  "KW": "Kuvajt",
  "KG": "Kirgistan",
  "LA": "Laos",
  "LV": "Latvija",
  "LB": "Libanon",
  "LS": "Lesoto",
  "LR": "Liberija",
  "LY": "Libija",
  "LI": "Lihtenštajn",
  "LT": "Litva",
  "LU": "Luxemburg",
  "MO": "Makao",
  "MK": "Sjeverna Makedonija",
  "MG": "Madagaskar",
  "MW": "Malavi",
  "MY": "Malazija",
  "MV": "Maldivi",
  "ML": "Mali",
  "MT": "Malta",
  "MH": "Maršalovi Otoci",
  "MQ": "Martinique",
  "MR": "Mauretanija",
  "MU": "Mauricijus",
  "YT": "Mayotte",
  "MX": "Meksiko",
  "FM": "Mikronezija",
  "MD": "Moldavija",
  "MC": "Monako",
  "MN": "Mongolijaa",
  "ME": "Crna Gora",
  "MS": "Montserrat",
  "MA": "Maroko",
  "MZ": "Mozambik",
  "MM": "Mjanmar",
  "NA": "Namibija",
  "NR": "Nauru",
  "NP": "Nepal",
  "NL": "Nizozemska",
  "NC": "Nova Kaledonija",
  "NZ": "Novi Zeland",
  "NI": "Nikaragva",
  "NE": "Niger",
  "NG": "Nigerija",
  "NU": "Niue",
  "NF": "Otok Norfolk",
  "KP": "Sjeverna Koreja",
  "MP": "Sjevernomarijanski otoci",
  "NO": "Norveška",
  "OM": "Oman",
  "PK": "Pakistan",
  "PW": "Palau",
  "PS": "Palestinski teritoriji",
  "PA": "Panama",
  "PG": "Papua Nova Gvineja",
  "PY": "Paragvaj",
  "PE": "Peru",
  "PH": "Filipini",
  "PL": "Poljska",
  "PT": "Portugal",
  "PR": "Portoriko",
  "QA": "Katar",
  "RE": "Réunion",
  "RO": "Rumunjska",
  "RU": "Rusija",
  "RW": "Ruanda",
  "BL": "Sveti Bartolomej",
  "SH": "Sveta Helena",
  "KN": "Sveti Kitts",
  "LC": "Sveta Lucija",
  "MF": "Sveti Martin",
  "PM": "Sveti Petar i Mikelon",
  "VC": "Sveti Vincent",
  "WS": "Samoa",
  "SM": "San Marino",
  "ST": "Sveti Toma i Princip",
  "SA": "Saudijska Arabija",
  "SN": "Senegal",
  "RS": "Serbija",
  "SC": "Sejšeli",
  "SL": "Sijera Leone",
  "SG": "Singapur",
  "SX": "Sint Maarten",
  "SK": "Slovačka",
  "SI": "Slovenija",
  "SB": "Solomonski otoci",
  "SO": "Somalija",
  "ZA": "Južna Afrika",
  "GS": "Južna Georgija i otočje Južni Sandwich",
  "KR": "Južna Koreja",
  "SS": "Južni Sudan",
  "ES": "Španjolska",
  "LK": "Šri Lanka",
  "SD": "Sudan",
  "SR": "Surinam",
  "SJ": "Svalbard i Jan Mayen",
  "SZ": "Esvatini",
  "SE": "Švedska",
  "CH": "Švicarska",
  "SY": "Sirija",
  "TW": "Republika Kina",
  "TJ": "Tadžikistan",
  "TZ": "Tanzanija",
  "TH": "Tajland",
  "TG": "Togo",
  "TK": "Tokelau",
  "TO": "Tonga",
  "TT": "Trinidad i Tobago",
  "TN": "Tunis",
  "TR": "Turska",
  "TM": "Turkmenistan",
  "TC": "Otoci Turks i Caicos",
  "TV": "Tuvalu",
  "VI": "Američki Djevičanski otoci",
  "UG": "Uganda",
  "UA": "Ukrajina",
  "AE": "Ujedinjeni Arapski Emirati",
  "GB": "Ujedinjeno Kraljevstvo",
  "US": "Sjedinjene Američke Države",
  "UY": "Urugvaj",
  "UZ": "Uzbekistan",
  "VU": "Vanuatu",
  "VA": "Vatikan",
  "VE": "Venezuela",
  "VN": "Vijetnam",
  "WF": "Wallis i Futuna",
  "WW": "U Cijelom Svijetu",
  "EH": "Zapadna Sahara",
  "YE": "Jemen",
  "ZM": "Zambija",
  "ZW": "Zimbabve",
  "search": "Pretraži",
};
