Map<String, String> ht = {
  "AF": "Afganistan",
  "AX": "Zil Aland",
  "AL": "Albani",
  "DZ": "Aljeri",
  "AS": "Samoa Ameriken",
  "AD": "Andòra",
  "AO": "Angola",
  "AI": "Angilye",
  "AG": "Antiga ak Barbuda",
  "AR": "Ajantin",
  "AM": "Ameni",
  "AW": "Aruba",
  "AC": "Ley Latitid",
  "AU": "Ostrali",
  "AT": "Otrich",
  "AZ": "Azerbaydjan",
  "BS": "Bahamas",
  "BH": "Bareyn",
  "BD": "Bangladèch",
  "BB": "Barbado",
  "BY": "Belaris",
  "BE": "Beljik",
  "BZ": "Beliz",
  "BJ": "Benen",
  "BM": "Bermid",
  "BT": "Boutan",
  "BO": "Bolivi",
  "BA": "Bosni ak Ersegòvinn",
  "BW": "Boswana",
  "BR": "Brezil",
  "IO": "Teritwa Britanik nan Oseyan Indyen",
  "VG": "Zil Vèjini Britanik",
  "BN": "Briney",
  "BG": "Bilgari",
  "BF": "Burkina Faso",
  "BI": "Burundi",
  "KH": "Kambòdj",
  "CM": "Kameroun",
  "CA": "Kanada",
  "CV": "Capvèd",
  "BQ": "Karayib Nederlan",
  "KY": "Zil Kayman",
  "CF": "Repiblik Afriken Santral",
  "TD": "Tchad",
  "CL": "Chili",
  "CN": "Lachin",
  "CX": "Zil Nwèl",
  "CC": "Zil Kokòs (Kiling)",
  "CO": "Kolonbi",
  "KM": "Komò",
  "CD": "Kongo - Kinshasa",
  "CG": "Kongo - Brazzaville",
  "CK": "Zil Kook",
  "CR": "Kosta Rika",
  "CI": "Pèl Kòt Divwa",
  "HR": "Kwoasi",
  "CU": "Kiba",
  "CW": "Kurasao",
  "CY": "Sezi",
  "CZ": "Repiblik Chek",
  "DK": "Dannmak",
  "DJ": "Djibouti",
  "DM": "Dominik",
  "DO": "Repiblik Dominikèn",
  "TL": "Timò Lès",
  "EC": "Ekwater",
  "EG": "Lijip",
  "SV": "El Salvador",
  "GQ": "Gine ekwataryal",
  "ER": "Eritre",
  "EE": "Estoni",
  "ET": "Etiyopi",
  "FK": "Zil Falkland (Malwinn)",
  "FO": "Zil Faro",
  "FJ": "Fidji",
  "FI": "Finland",
  "FR": "Franse",
  "GF": "Gwiyann Franse",
  "PF": "Polinezi Franse",
  "GA": "Gabon",
  "GM": "Ganbi",
  "GE": "Jòjya",
  "DE": "Almay",
  "GH": "Gana",
  "GI": "Jibraltar",
  "GR": "Grès",
  "GL": "Gwoland",
  "GD": "Gwadloup",
  "GP": "Gwadloup",
  "GU": "Gwam",
  "GT": "Gwatmala",
  "GG": "Gèrzi",
  "GN": "Gine Konakry",
  "GW": "Gine-Bisau",
  "GY": "Giyàn",
  "HT": "Ayiti",
  "HM": "Zil Herd ak McDonald",
  "HN": "ondirès",
  "HK": "Hong Kong",
  "HU": "Ongri",
  "IS": "Iceland",
  "IN": "Lend",
  "ID": "Indonezi",
  "IR": "Iran",
  "IQ": "Irak",
  "IE": "Iland",
  "IM": "Zil Man",
  "IL": "Izrayèl",
  "IT": "Itali",
  "JM": "Jamayik",
  "JP": "Japon",
  "JE": "Djèrsi",
  "JO": "Zòdann",
  "KZ": "Kazakstan",
  "KE": "Kenya",
  "KI": "Kiribati",
  "XK": "Kosovo",
  "KW": "Kowet",
  "KG": "Kirgistan",
  "LA": "Lawòt",
  "LV": "Letoni",
  "LB": "Liban",
  "LS": "Lesoto",
  "LR": "Liberiya",
  "LY": "Libi",
  "LI": "Liktenstèn",
  "LT": "Lityani",
  "LU": "Liksanbou",
  "MO": "Makao",
  "MK": "Masedwàn",
  "MG": "Madagaskar",
  "MW": "Malawi",
  "MY": "Malezi",
  "MV": "Maldiv",
  "ML": "Mali",
  "MT": "Malt",
  "MH": "Zil Marshall",
  "MQ": "Matinik",
  "MR": "Moritani",
  "MU": "Moris",
  "YT": "Mayòt",
  "MX": "Meksik",
  "FM": "Mikwonezi",
  "MD": "Moldavi",
  "MC": "Monako",
  "MN": "Mongoli",
  "ME": "Montenegro",
  "MS": "Montsera",
  "MA": "Marok",
  "MZ": "Mozanbik",
  "MM": "Myanmar (Birman)",
  "NA": "Namibi",
  "NR": "Nauru",
  "NP": "Nepal",
  "NL": "Peyiba",
  "NC": "Nouvel Kaledoni",
  "NZ": "Zeland Nouvèl",
  "NI": "Nikaragua",
  "NE": "Nizer",
  "NG": "Nijerya",
  "NU": "Niwe",
  "NF": "Zil Norfolk",
  "KP": "Korè di Nò",
  "MP": "Zil Maryann di Nò",
  "NO": "Nòvej",
  "OM": "Oman",
  "PK": "Pakistan",
  "PW": "Palaos",
  "PS": "Teritwa Palestinyen yo",
  "PA": "Panama",
  "PG": "Papwa-Nouvel-Gine",
  "PY": "Paraguay",
  "PE": "Perou",
  "PH": "Filipin",
  "PL": "Polòy",
  "PT": "Pòtigal",
  "PR": "Pòtoriko",
  "QA": "Katari",
  "RE": "Reyonyon",
  "RO": "Roumani",
  "RU": "Lwisi",
  "RW": "Rwanda",
  "BL": "Sen-Batist",
  "SH": "Sainte Len",
  "KN": "Sen-Kits ak Nevis",
  "LC": "Sen-Lisi",
  "MF": "Sen-Marten",
  "PM": "Sen-Pyè ak Mikelon",
  "VC": "Sen-Vensan ak Grenadin",
  "WS": "Samoa",
  "SM": "San Marino",
  "ST": "São Tomé ak Prínsip",
  "SA": "Larabi Saoudit",
  "SN": "Senegal",
  "RS": "Serbi",
  "SC": "Sesel",
  "SL": "Siyera Lewòn",
  "SG": "Sinapour",
  "SX": "Saint-Martin (Pays-Bas)",
  "SK": "Slovak",
  "SI": "Sloveni",
  "SB": "Zil Salomon",
  "SO": "Somali",
  "ZA": "Afrik di Sid",
  "GS": "Jòjya di Sid ak Zil Sandwich di Sid",
  "KR": "Korè di Sid",
  "SS": "Sid Soudan",
  "ES": "Panyòl",
  "LK": "Siri Lanka",
  "SD": "Soudan",
  "SR": "Sirinam",
  "SJ": "Svalbard ak Jan Mayen",
  "SZ": "Eswatini",
  "SE": "Lond",
  "CH": "Laswis",
  "SY": "Syri",
  "TW": "Taywan",
  "TJ": "Tadjikistan",
  "TZ": "Tanzani",
  "TH": "Taylann",
  "TG": "Togo",
  "TK": "Tokelau",
  "TO": "Tonga",
  "TT": "Trinite ak Tobago",
  "TN": "Tinizi",
  "TR": "Tikèy",
  "TM": "Turkmanistan",
  "TC": "Zil Turks ak Caïcos",
  "TV": "Tuvalu",
  "VI": "Zil Vèjini Ameriken",
  "UG": "Ouganda",
  "UA": "Ikrenn",
  "AE": "Emira Arab Ini",
  "GB": "Rwayòm Ini",
  "US": "Leta Zini",
  "UY": "Irigwey",
  "UZ": "Ouzbekistan",
  "VU": "Vanwatou",
  "VA": "Site Vatican",
  "VE": "Venezwela",
  "VN": "Viyetnam",
  "WF": "Wallis ak Futuna",
  "WW": "Lanmò",
  "EH": "Sahara di Sid",
  "YE": "Yemèn",
  "ZM": "Zanbi",
  "ZW": "Zimbabwe",
  "search": "Chèche",
};