Map<String, String> id = {
  "AF": 'Afghanistan',
  "AX": 'Aland',
  "AL": 'Albania',
  "DZ": 'Aljazair',
  "AS": 'Samoa Amerika',
  "AD": 'Andorra',
  "AO": 'Angola',
  "AI": 'Anguilla',
  "AG": 'Antigua dan Barbuda',
  "AR": 'Argentina',
  "AM": 'Armenia',
  "AW": 'Aruba',
  "AC": 'Ascension Island',
  "AU": 'Australia',
  "AT": 'Austria',
  "AZ": 'Azerbaijan',
  "BS": 'Bahamas',
  "BH": 'Bahrain',
  "BD": 'Bangladesh',
  "BB": 'Barbados',
  "BY": 'Belarusia',
  "BE": 'Belgia',
  "BZ": 'Belize',
  "BJ": 'Benin',
  "BM": 'Bermuda',
  "BT": 'Bhutan',
  "BO": 'Bolivia',
  "BA": 'Bosnia and Herzegovina',
  "BW": 'Botswana',
  "BR": 'Brazil',
  "IO": 'Wilayah Samudera Hindia Britania',
  "VG": 'Kepulauan Virgin Britania',
  "BN": 'Brunei',
  "BG": 'Bulgaria',
  "BF": 'Burkina Faso',
  "BI": 'Burundi',
  "KH": 'Kamboja',
  "CM": 'Kamerun',
  "CA": 'Kanada',
  "CV": 'Cape Verde',
  "BQ": 'Belanda Karibia',
  "KY": 'Kepulauan Cayman',
  "CF": 'Republik Afrika Tengah',
  "TD": 'Chad',
  "CL": 'Chile',
  "CN": 'China',
  "CX": 'Pulau Natal',
  "CC": 'Kepulauan Cocos (Keeling)',
  "CO": 'Kolombia',
  "KM": 'Comoros',
  "CD": 'Republik Demokratik Kongo',
  "CG": 'Republik Kongo',
  "CK": 'Kepulauan Cook',
  "CR": 'Kostarika',
  "CI": 'Pantai Gading',
  "HR": 'Kroasia',
  "CU": 'Kuba',
  "CW": 'Curaçao',
  "CY": 'Siprus',
  "CZ": 'Republik Ceko',
  "DK": 'Denmark',
  "DJ": 'Djibouti',
  "DM": 'Dominika',
  "DO": 'Republik Dominika',
  "TL": 'Timor Leste',
  "EC": 'Ekuador',
  "EG": 'Mesir',
  "SV": 'El Salvador',
  "GQ": 'Guinea Khatulistiwa',
  "ER": 'Eritrea',
  "EE": 'Estonia',
  "ET": 'Ethiopia',
  "FK": 'Kepulauan Falkland',
  "FO": 'Kepulauan Faroe',
  "FJ": 'Fiji',
  "FI": 'Finlandia',
  "FR": 'Prancis',
  "GF": 'French Guiana',
  "PF": 'French Polynesia',
  "GA": 'Gabon',
  "GM": 'Gambia',
  "GE": 'Georgia',
  "DE": 'Jerman',
  "GH": 'Ghana',
  "GI": 'Gibraltar',
  "GR": 'Yunani',
  "GL": 'Greenland',
  "GD": 'Grenada',
  "GP": 'Guadeloupe',
  "GU": 'Guam',
  "GT": 'Guatemala',
  "GG": 'Guernsey',
  "GN": 'Guinea',
  "GW": 'Guinea-Bissau',
  "GY": 'Guyana',
  "HT": 'Haiti',
  "HM": 'Heard Island and McDonald Islands',
  "HN": 'Honduras',
  "HK": 'Hongkong',
  "HU": 'Hungaria',
  "IS": 'Islandia',
  "IN": 'India',
  "ID": 'Indonesia',
  "IR": 'Iran',
  "IQ": 'Irak',
  "IE": 'Irlandia',
  "IM": 'Pulau Man',
  "IL": 'Israel',
  "IT": 'Italia',
  "JM": 'Jamaika',
  "JP": 'Jepang',
  "JE": 'Jersey',
  "JO": 'Yordania',
  "KZ": 'Kazakhstan',
  "KE": 'Kenya',
  "KI": 'Kiribati',
  "XK": 'Kosovo',
  "KW": 'Kuwait',
  "KG": 'Kyrgyzstan',
  "LA": 'Laos',
  "LV": 'Latvia',
  "LB": 'Lebanon',
  "LS": 'Lesotho',
  "LR": 'Liberia',
  "LY": 'Libya',
  "LI": 'Liechtenstein',
  "LT": 'Lithuania',
  "LU": 'Luksemburg',
  "MO": 'Makau',
  "MK": 'Makedonia Utara',
  "MG": 'Madagaskar',
  "MW": 'Malawi',
  "MY": 'Malaysia',
  "MV": 'Maladewa',
  "ML": 'Mali',
  "MT": 'Malta',
  "MH": 'Kepulauan Marshall',
  "MQ": 'Martinik',
  "MR": 'Mauritania',
  "MU": 'Mauritius',
  "YT": 'Mayotte',
  "MX": 'Meksiko',
  "FM": 'Mikronesia',
  "MD": 'Moldova',
  "MC": 'Monako',
  "MN": 'Mongolia',
  "ME": 'Montenegro',
  "MS": 'Montserrat',
  "MA": 'Maroko',
  "MZ": 'Mozambik',
  "MM": 'Myanmar',
  "NA": 'Namibia',
  "NR": 'Nauru',
  "NP": 'Nepal',
  "NL": 'Belanda',
  "NC": 'Kaledonia Baru',
  "NZ": 'Selandia Baru',
  "NI": 'Nicaragua',
  "NE": 'Niger',
  "NG": 'Nigeria',
  "NU": 'Niue',
  "NF": 'Kepulauan Norfolk',
  "KP": 'Korea Utara',
  "MP": 'Kepulauan Mariana Utara',
  "NO": 'Norwegia',
  "OM": 'Oman',
  "PK": 'Pakistan',
  "PW": 'Palau',
  "PS": 'Palestina',
  "PA": 'Panama',
  "PG": 'Papua Nugini',
  "PY": 'Paraguay',
  "PE": 'Peru',
  "PH": 'Filipina',
  "PL": 'Polandia',
  "PT": 'Portugal',
  "PR": 'Puerto Riko',
  "QA": 'Qatar',
  "RE": 'Reunion',
  "RO": 'Rumania',
  "RU": 'Rusia',
  "RW": 'Rwanda',
  "BL": 'Saint Barthélemy',
  "SH": 'Saint Helena, Ascension and Tristan da Cunha',
  "KN": 'Saint Kitts and Nevis',
  "LC": 'Saint Lucia',
  "MF": 'Saint Martin',
  "PM": 'Saint Pierre dan Miquelon',
  "VC": 'Saint Vincent and the Grenadines',
  "WS": 'Samoa',
  "SM": 'San Marino',
  "ST": 'São Tomé and Príncipe',
  "SA": 'Arab Saudi',
  "SN": 'Senegal',
  "RS": 'Serbia',
  "SC": 'Seychelles',
  "SL": 'Sierra Leone',
  "SG": 'Singapura',
  "SX": 'Sint Maarten',
  "SK": 'Slovakia',
  "SI": 'Slovenia',
  "SB": 'Kepulauan Solomon',
  "SO": 'Somalia',
  "ZA": 'Afrika Selatan',
  "GS": 'Georgia Selatan',
  "KR": 'Korea Selatan',
  "SS": 'Sudan Selatan',
  "ES": 'Spanyol',
  "LK": 'Sri Lanka',
  "SD": 'Sudan',
  "SR": 'Suriname',
  "SJ": 'Svalbard and Jan Mayen',
  "SZ": 'Kerajaan Eswatini',
  "SE": 'Swedia',
  "CH": 'Swiss',
  "SY": 'Suriah',
  "TW": 'Taiwan',
  "TJ": 'Tajikistan',
  "TZ": 'Tanzania',
  "TH": 'Thailand',
  "TG": 'Togo',
  "TK": 'Tokelau',
  "TO": 'Tonga',
  "TT": 'Trinidad and Tobago',
  "TN": 'Tunisia',
  "TR": 'Turki',
  "TM": 'Turkmenistan',
  "TC": 'Kepulauan Turks and Caicos',
  "TV": 'Tuvalu',
  "VI": 'Kepulauan Virgin Amerika Serikat',
  "UG": 'Uganda',
  "UA": 'Ukraina',
  "AE": 'Uni Emirat Arab',
  "GB": 'Britania Raya',
  "US": 'Amerika Serikat',
  "UY": 'Uruguay',
  "UZ": 'Uzbekistan',
  "VU": 'Vanuatu',
  "VA": 'Vatikan',
  "VE": 'Venezuela',
  "VN": 'Vietnam',
  "WF": 'Wallis and Futuna',
  "WW": 'Worldwide',
  "EH": 'Sahara Barat',
  "YE": 'Yaman',
  "ZM": 'Zambia',
  "ZW": 'Zimbabwe',
  "search": 'Mencari',
};
