// Can't use is - as it's a reserved word in Dart, so use is_ instead
Map<String, String> is_ = {
  "AF": "Afganistan",
  "AX": "Álandseyjar",
  "AL": "Albanía",
  "DZ": "Alsír",
  "AS": "Bandaríska Samóa",
  "AD": "Andorra",
  "AO": "Angóla",
  "AI": "Angvilla",
  "AG": "Antígva og Barbúda",
  "AR": "Argentína",
  "AM": "Armenía",
  "AW": "Arúba",
  "AC": "Ascension-eyja",
  "AU": "Ástralía",
  "AT": "Austurríki",
  "AZ": "Aserbaídsjan",
  "BS": "Bahamaeyjar",
  "BH": "Barein",
  "BD": "Bangladess",
  "BB": "Barbados",
  "BY": "Hvíta-Rússland",
  "BE": "Belgía",
  "BZ": "Belís",
  "BJ": "Benín",
  "BM": "Bermúdaeyjar",
  "BT": "Bútan",
  "BO": "Bólivía",
  "BA": "Bosnía og Hersegóvína",
  "BW": "Botsvana",
  "BR": "Brasilía",
  "IO": "Bresku Indlandshafsyfirráðin",
  "VG": "Bresku Jómfrúaeyjar",
  "BN": "Brúnei",
  "BG": "Búlgaría",
  "BF": "Búrkína Fasó",
  "BI": "Búrúndí",
  "KH": "Kambódía",
  "CM": "Kamerún",
  "CA": "Kanada",
  "CV": "Grænhöfðaeyjar",
  "BQ": "Karíbahafshluti Hollands",
  "KY": "Caymaneyjar",
  "CF": "Mið-Afríkulýðveldið",
  "TD": "Tsjad",
  "CL": "Síle",
  "CN": "Kína",
  "CX": "Jólaeyja",
  "CC": "Kókoseyjar",
  "CO": "Kólumbía",
  "KM": "Kómoreyjar",
  "CD": "Austur-Kongó",
  "CG": "Vestur-Kongó",
  "CK": "Cookseyjar",
  "CR": "Kosta Ríka",
  "CI": "Fílabeinsströndin",
  "HR": "Króatía",
  "CU": "Kúba",
  "CW": "Curacao",
  "CY": "Kýpur",
  "CZ": "Tékkland",
  "DK": "Danmörk",
  "DJ": "Djíbútí",
  "DM": "Dóminíka",
  "DO": "Dóminíska lýðveldið",
  "TL": "Austur-Tímor",
  "EC": "Ekvador",
  "EG": "Egyptaland",
  "SV": "El Salvaðor",
  "GQ": "Miðbaugs-Gínea",
  "ER": "Erítrea",
  "EE": "Eistland",
  "ET": "Eþíópía",
  "FK": "Falklandseyjar",
  "FO": "Færeyjar",
  "FJ": "Fídjieyjar",
  "FI": "Finnland",
  "FR": "Frakkland",
  "GF": "Franska Gvæjana",
  "PF": "Franska Pólýnesía",
  "GA": "Gabon",
  "GM": "Gambía",
  "GE": "Georgía",
  "DE": "Þýskaland",
  "GH": "Gana",
  "GI": "Gíbraltar",
  "GR": "Grikkland",
  "GL": "Grænland",
  "GD": "Grenada",
  "GP": "Gvadelúpeyjar",
  "GU": "Gvam",
  "GT": "Gvatemala",
  "GG": "Guerney",
  "GN": "Gínea",
  "GW": "Gínea-Bissá",
  "GY": "Gvæjana",
  "HT": "Haítí",
  "HM": "Heard og McDonaldseyjar",
  "HN": "Hondúras",
  "HK": "Hong Kong",
  "HU": "Ungverjaland",
  "IS": "Ísland",
  "IN": "Indland",
  "ID": "Indónesía",
  "IR": "Íran",
  "IQ": "Írak",
  "IE": "Írland",
  "IM": "Mön",
  "IL": "Ísrael",
  "IT": "Ítalía",
  "JM": "Jamaíka",
  "JP": "Japan",
  "JE": "Jersey",
  "JO": "Jórdanía",
  "KZ": "Kasakstan",
  "KE": "Kenía",
  "KI": "Kíribatí",
  "XK": "Kósovó",
  "KW": "Kúveit",
  "KG": "Kirgistan",
  "LA": "Laos",
  "LV": "Lettland",
  "LB": "Líbanon",
  "LS": "Lesótó",
  "LR": "Líbería",
  "LY": "Líbýa",
  "LI": "Liechtenstein",
  "LT": "Litháen",
  "LU": "Lúxemborg",
  "MO": "Makaó",
  "MK": "Norður-Makedónía",
  "MG": "Madagaskar",
  "MW": "Malaví",
  "MY": "Malasía",
  "MV": "Maldíveyjar",
  "ML": "Malí",
  "MT": "Malta",
  "MH": "Marshallseyjar",
  "MQ": "Martiník",
  "MR": "Máritanía",
  "MU": "Máritíus",
  "YT": "Mayotte",
  "MX": "Mexíkó",
  "FM": "Míkrónesía",
  "MD": "Moldóva",
  "MD2": "Transnistría",
  "MC": "Mónakó",
  "MN": "Mongólía",
  "ME": "Svartfjallaland",
  "MS": "Montserrat",
  "MA": "Marokkó",
  "MZ": "Mósambík",
  "MM": "Mjanmar",
  "NA": "Namíbía",
  "NR": "Nárú",
  "NP": "Nepal",
  "NL": "Holland",
  "NC": "Nýja-Kaledónía",
  "NZ": "Nýja-Sjáland",
  "NI": "Níkaragva",
  "NE": "Níger",
  "NG": "Nígería",
  "NU": "Niue",
  "NF": "Norfolkeyja",
  "KP": "Norður-Kórea",
  "MP": "Norður-Maríanaeyjar",
  "NO": "Noregur",
  "OM": "Óman",
  "PK": "Pakistan",
  "PW": "Palá",
  "PS": "Palestínska heimastjórnin",
  "PA": "Panama",
  "PG": "Papúa Nýja-Gínea",
  "PY": "Paragvæ",
  "PE": "Perú",
  "PH": "Filippseyjar",
  "PL": "Pólland",
  "PT": "Portúgal",
  "PR": "Púertó Ríkó",
  "QA": "Katar",
  "RE": "Réunion",
  "RO": "Rúmenía",
  "RU": "Rússland",
  "RW": "Rúanda",
  "BL": "Sankti Bartólómeusareyjar",
  "SH": "Sankti Helena",
  "KN": "Sankti Kristófer og Nevis",
  "LC": "Sankti Lúsía",
  "MF": "Sankti Martin",
  "PM": "Sankti Pierre og Miquelon",
  "VC": "Sankti Vinsent og Grenadíneyjar",
  "WS": "Samóa",
  "SM": "San Marínó",
  "ST": "Saó Tóme og Prinsípe",
  "SA": "Sádi-Arabía",
  "SN": "Senegal",
  "RS": "Serbía",
  "SC": "Seychelles-eyjar",
  "SL": "Síerra Leóne",
  "SG": "Singapúr",
  "SX": "Sankti Martin (hollenski hluti)",
  "SK": "Slóvakía",
  "SI": "Slóvenía",
  "SB": "Salómonseyjar",
  "SO": "Sómalía",
  "ZA": "Suður-Afríka",
  "GS": "Suður-Georgía og Suður-Sandvíkureyjar",
  "KR": "Suður-Kórea",
  "SS": "Suður-Súdan",
  "ES": "Spánn",
  "LK": "Srí Lanka",
  "SD": "Súdan",
  "SR": "Súrínam",
  "SJ": "Svalbarði og Jan Mayen",
  "SZ": "Esvatíní",
  "SE": "Svíþjóð",
  "CH": "Sviss",
  "SY": "Sýrland",
  "TW": "Taívan",
  "TJ": "Tadsjikistan",
  "TZ": "Tansanía",
  "TH": "Taíland",
  "TG": "Tógó",
  "TK": "Tókelá",
  "TO": "Tonga",
  "TT": "Trínidad og Tóbagó",
  "TN": "Túnis",
  "TR": "Tyrkland",
  "TM": "Túrkmenistan",
  "TC": "Turks- og Caicoseyjar",
  "TV": "Túvalú",
  "VI": "Bandarísku Jómfrúaeyjar",
  "UG": "Úganda",
  "UA": "Úkraína",
  "AE": "Sameinuðu arabísku furstadæmin",
  "GB": "Bretland",
  "US": "Bandaríkin",
  "UY": "Úrúgvæ",
  "UZ": "Úsbekistan",
  "VU": "Vanúatú",
  "VA": "Vatíkanið",
  "VE": "Venesúela",
  "VN": "Víetnam",
  "WF": "Wallis- og Fútúnaeyjar",
  "WW": "Heimurinn",
  "EH": "Vestur-Sahara",
  "YE": "Jemen",
  "ZM": "Sambía",
  "ZW": "Simbabve",
  "search": "Leita",
};
