Map<String, String> it = {
  "AF": "Afghanistan",
  "AX": "Isole Aland",
  "AL": "Albania",
  "DZ": "Algeria",
  "AS": "Samoa americane",
  "AD": "Andorra",
  "AO": "Angola",
  "AI": "Anguilla",
  "AG": "Antigua e Barbuda",
  "AR": "Argentina",
  "AM": "Armenia",
  "AW": "Aruba",
  "AC": "Isola di Ascensione",
  "AU": "Australia",
  "AT": "Austria",
  "AZ": "Azerbaigian",
  "BS": "Bahamas",
  "BH": "Bahrein",
  "BD": "Bangladesh",
  "BB": "Barbados",
  "BY": "Bielorussia",
  "BE": "Belgio",
  "BZ": "Belize",
  "BJ": "Benin",
  "BM": "Bermuda",
  "BT": "Bhutan",
  "BO": "Bolivia",
  "BA": "Bosnia ed Erzegovina",
  "BW": "Botswana",
  "BR": "Brasile",
  "IO": "Territorio britannico dell'oceano Indiano",
  "VG": "Isole Vergini britanniche",
  "BN": "Brunei",
  "BG": "Bulgaria",
  "BF": "Burkina Faso",
  "BI": "Burundi",
  "KH": "Cambogia",
  "CM": "Camerun",
  "CA": "Canada",
  "CV": "Capo Verde",
  "BQ": "Paesi Bassi caraibici",
  "KY": "Isole Cayman",
  "CF": "Repubblica Centrafricana",
  "TD": "Ciad",
  "CL": "Cile",
  "CN": "Cina",
  "CX": "Isola di Natale",
  "CC": "Isole Cocos [Keeling]",
  "CO": "Colombia",
  "KM": "Comore",
  "CD": "Repubblica Democratica del Congo",
  "CG": "Congo",
  "CK": "Isole Cook",
  "CR": "Costa Rica",
  "CI": "Costa d'Avorio",
  "HR": "Croazia",
  "CU": "Cuba",
  "CW": "Curaçao",
  "CY": "Cipro",
  "CZ": "Repubblica Ceca",
  "DK": "Danimarca",
  "DJ": "Gibuti",
  "DM": "Dominica",
  "DO": "Repubblica Dominicana",
  "TL": "Timor Est",
  "EC": "Ecuador",
  "EG": "Egitto",
  "SV": "El Salvador",
  "GQ": "Guinea Equatoriale",
  "ER": "Eritrea",
  "EE": "Estonia",
  "ET": "Etiopia",
  "FK": "Isole Falkland [Malvine]",
  "FO": "Isole Faroe",
  "FJ": "Figi",
  "FI": "Finlandia",
  "FR": "Francia",
  "GF": "Guyana francese",
  "PF": "Polinesia francese",
  "GA": "Gabon",
  "GM": "Gambia",
  "GE": "Georgia",
  "DE": "Germania",
  "GH": "Ghana",
  "GI": "Gibilterra",
  "GR": "Grecia",
  "GL": "Groenlandia",
  "GD": "Grenada",
  "GP": "Guadalupa",
  "GU": "Guam",
  "GT": "Guatemala",
  "GG": "Guernsey",
  "GN": "Guinea Conakry",
  "GW": "Guinea-Bissau",
  "GY": "Guyana",
  "HT": "Haiti",
  "HM": "Isole Heard e McDonald",
  "HN": "Honduras",
  "HK": "Hong Kong",
  "HU": "Ungheria",
  "IS": "Islanda",
  "IN": "India",
  "ID": "Indonesia",
  "IR": "Iran",
  "IQ": "Iraq",
  "IE": "Irlanda",
  "IM": "Isola di Man",
  "IL": "Israele",
  "IT": "Italia",
  "JM": "Giamaica",
  "JP": "Giappone",
  "JE": "Jersey",
  "JO": "Giordania",
  "KZ": "Kazakistan",
  "KE": "Kenya",
  "KI": "Kiribati",
  "XK": "Kosovo",
  "KW": "Kuwait",
  "KG": "Kirghizistan",
  "LA": "Laos",
  "LV": "Lettonia",
  "LB": "Libano",
  "LS": "Lesotho",
  "LR": "Liberia",
  "LY": "Libia",
  "LI": "Liechtenstein",
  "LT": "Lituania",
  "LU": "Lussemburgo",
  "MO": "Macao",
  "MK": "Macedonia del Nord",
  "MG": "Madagascar",
  "MW": "Malawi",
  "MY": "Malesia",
  "MV": "Maldive",
  "ML": "Mali",
  "MT": "Malta",
  "MH": "Isole Marshall",
  "MQ": "Martinica",
  "MR": "Mauritania",
  "MU": "Mauritius",
  "YT": "Mayotte",
  "MX": "Messico",
  "FM": "Micronesia",
  "MD": "Moldavia",
  "MC": "Monaco",
  "MN": "Mongolia",
  "ME": "Montenegro",
  "MS": "Montserrat",
  "MA": "Marocco",
  "MZ": "Mozambico",
  "MM": "Myanmar",
  "NA": "Namibia",
  "NR": "Nauru",
  "NP": "Nepal",
  "NL": "Paesi Bassi",
  "NC": "Nuova Caledonia",
  "NZ": "Nuova Zelanda",
  "NI": "Nicaragua",
  "NE": "Niger",
  "NG": "Nigeria",
  "NU": "Niue",
  "NF": "Isola Norfolk",
  "KP": "Corea del Nord",
  "MP": "Isole Marianne Settentrionali",
  "NO": "Norvegia",
  "OM": "Oman",
  "PK": "Pakistan",
  "PW": "Palau",
  "PS": "Territori Palestinesi",
  "PA": "Panama",
  "PG": "Papua Nuova Guinea",
  "PY": "Paraguay",
  "PE": "Perù",
  "PH": "Filippine",
  "PL": "Polonia",
  "PT": "Portogallo",
  "PR": "Portorico",
  "QA": "Qatar",
  "RE": "Réunion",
  "RO": "Romania",
  "RU": "Russia",
  "RW": "Ruanda",
  "BL": "Saint Barthélemy",
  "SH": "Sant'Elena",
  "KN": "Saint Kitts e Nevis",
  "LC": "Saint Lucia",
  "MF": "Saint Martin",
  "PM": "Saint Pierre e Miquelon",
  "VC": "Saint Vincent e Grenadine",
  "WS": "Samoa",
  "SM": "San Marino",
  "ST": "São Tomé e Príncipe",
  "SA": "Arabia Saudita",
  "SN": "Senegal",
  "RS": "Serbia",
  "SC": "Seychelles",
  "SL": "Sierra Leone",
  "SG": "Singapore",
  "SX": "Sint Maarten",
  "SK": "Slovacchia",
  "SI": "Slovenia",
  "SB": "Isole Salomone",
  "SO": "Somalia",
  "ZA": "Sud Africa",
  "GS": "Georgia del Sud e Isole Sandwich Meridionali",
  "KR": "Corea del Sud",
  "SS": "Sud Sudan",
  "ES": "Spagna",
  "LK": "Sri Lanka",
  "SD": "Sudan",
  "SR": "Suriname",
  "SJ": "Svalbard e Jan Mayen",
  "SZ": "Eswatini",
  "SE": "Svezia",
  "CH": "Svizzera",
  "SY": "Siria",
  "TW": "Taiwan",
  "TJ": "Tagikistan",
  "TZ": "Tanzania",
  "TH": "Thailandia",
  "TG": "Togo",
  "TK": "Tokelau",
  "TO": "Tonga",
  "TT": "Trinidad e Tobago",
  "TN": "Tunisia",
  "TR": "Turchia",
  "TM": "Turkmenistan",
  "TC": "Isole Turks e Caicos",
  "TV": "Tuvalu",
  "VI": "Isole Vergini americane",
  "UG": "Uganda",
  "UA": "Ucraina",
  "AE": "Emirati Arabi Uniti",
  "GB": "Regno Unito",
  "US": "Stati Uniti",
  "UY": "Uruguay",
  "UZ": "Uzbekistan",
  "VU": "Vanuatu",
  "VA": "Città del Vaticano",
  "VE": "Venezuela",
  "VN": "Vietnam",
  "WF": "Wallis e Futuna",
  "WW": "Mondo",
  "EH": "Sahara Occidentale",
  "YE": "Yemen",
  "ZM": "Zambia",
  "ZW": "Zimbabwe",
  "search": "Cerca",
};
