Map<String, String> lt = {
  "AF": "Afganistanas",
  "AX": "Alandai",
  "AL": "Albanija",
  "DZ": "Alžyras",
  "AS": "Amerikos Samoa",
  "AD": "Andora",
  "AO": "Angola",
  "AI": "Angilija",
  "AG": "Antigva ir Barbuda",
  "AR": "Argentina",
  "AM": "Armėnija",
  "AW": "Aruba",
  "AC": "Dangun Žengimo sala",
  "AU": "Australija",
  "AT": "Austrija",
  "AZ": "Azerbaidžanas",
  "BS": "Bahamos",
  "BH": "Bahreinas",
  "BD": "Bangladešas",
  "BB": "Barbadosas",
  "BY": "Baltarusija",
  "BE": "Belgija",
  "BZ": "Belizas",
  "BJ": "Beninas",
  "BM": "Bermuda",
  "BT": "Butanas",
  "BO": "Bolivija",
  "BA": "Bosnija ir Hercegovina",
  "BW": "Botsvana",
  "BR": "Brazilija",
  "IO": "Indijos vandenyno britų salos",
  "VG": "Didžiosios Britanijos Mergelių salos",
  "BN": "Brunėjus",
  "BG": "Bulgarija",
  "BF": "Burkina Fasas",
  "BI": "Burundis",
  "KH": "Kambodža",
  "CM": "Kamerūnas",
  "CA": "Kanada",
  "CV": "Žaliasis Kyšulys",
  "BQ": "Karibų Nyderlandai",
  "KY": "Kaimanų salos",
  "CF": "Centrinės Afrikos Respublika",
  "TD": "Čadas",
  "CL": "Čilė",
  "CN": "Kinija",
  "CX": "Kalėdų sala",
  "CC": "Kokosų salos",
  "CO": "Kolumbija",
  "KM": "Komorai",
  "CD": "Kongo Demokratinė Respublika",
  "CG": "Kongas",
  "CK": "Kuko salos",
  "CR": "Kosta Rika",
  "CI": "Dramblio Kaulo Krantas",
  "HR": "Kroatija",
  "CU": "Kuba",
  "CW": "Kiurasao",
  "CY": "Kipras",
  "CZ": "Čekija",
  "DK": "Danija",
  "DJ": "Džibutis",
  "DM": "Dominika",
  "DO": "Dominikos Respublika",
  "TL": "Rytų Timoras",
  "EC": "Ekvadoras",
  "EG": "Egiptas",
  "SV": "Salvadoras",
  "GQ": "Pusiaujo Gvinėja",
  "ER": "Eritrėja",
  "EE": "Estija",
  "ET": "Etiopija",
  "FK": "Falklando salos",
  "FO": "Farerų salos",
  "FJ": "Fidžis",
  "FI": "Suomija",
  "FR": "Prancūzija",
  "GF": "Prancūzijos Gviana",
  "PF": "Prancūzijos Polinezija",
  "GA": "Gabonas",
  "GM": "Gambija",
  "GE": "Gruzija",
  "DE": "Vokietija",
  "GH": "Gana",
  "GI": "Gibraltaras",
  "GR": "Graikija",
  "GL": "Grenlandija",
  "GD": "Grenada",
  "GP": "Gvadelupa",
  "GU": "Guamas",
  "GT": "Gvatemala",
  "GG": "Gernsis",
  "GN": "Gvinėja",
  "GW": "Bisau Gvinėja",
  "GY": "Gajana",
  "HT": "Haitis",
  "HM": "Herdo ir Makdonaldo salos",
  "HN": "Hondūras",
  "HK": "Honkongas",
  "HU": "Vengrija",
  "IS": "Islandija",
  "IN": "Indija",
  "ID": "Indonezija",
  "IR": "Iranas",
  "IQ": "Irakas",
  "IE": "Airija",
  "IM": "Meno sala",
  "IL": "Izraelis",
  "IT": "Italija",
  "JM": "Jamaika",
  "JP": "Japonija",
  "JE": "Džersis",
  "JO": "Jordanija",
  "KZ": "Kazachstanas",
  "KE": "Kenija",
  "KI": "Kiribatis",
  "XK": "Kosovas",
  "KW": "Kuveitas",
  "KG": "Kirgizija",
  "LA": "Laosas",
  "LV": "Latvija",
  "LB": "Libanas",
  "LS": "Lesotas",
  "LR": "Liberija",
  "LY": "Libija",
  "LI": "Lichtenšteinas",
  "LT": "Lietuva",
  "LU": "Liuksemburgas",
  "MO": "Makao",
  "MK": "Šiaurės Makedonija",
  "MG": "Madagaskaras",
  "MW": "Malavis",
  "MY": "Malaizija",
  "MV": "Maldyvai",
  "ML": "Malis",
  "MT": "Malta",
  "MH": "Maršalo Salos",
  "MQ": "Martinika",
  "MR": "Mauritanija",
  "MU": "Mauricijus",
  "YT": "Majotas",
  "MX": "Meksika",
  "FM": "Mikronezijos Federacinės Valstijos",
  "MD": "Moldavija",
  "MC": "Monakas",
  "MN": "Mongolija",
  "ME": "Juodkalnija",
  "MS": "Montseratas",
  "MA": "Marokas",
  "MZ": "Mozambikas",
  "MM": "Mianmaras",
  "NA": "Namibija",
  "NR": "Nauru",
  "NP": "Nepalas",
  "NL": "Nyderlandai",
  "NC": "Naujoji Kaledonija",
  "NZ": "Naujoji Zelandija",
  "NI": "Nikaragva",
  "NE": "Nigeris",
  "NG": "Nigerija",
  "NU": "Niujė",
  "NF": "Norfolkas",
  "KP": "Šiaurės Korėja",
  "MP": "Marianos šiaurinės salos",
  "NO": "Norvegija",
  "OM": "Omanas",
  "PK": "Pakistanas",
  "PW": "Palau",
  "PS": "Palestina",
  "PA": "Panama",
  "PG": "Papua Naujoji Gvinėja",
  "PY": "Paragvajus",
  "PE": "Peru",
  "PH": "Filipinai",
  "PL": "Lenkija",
  "PT": "Portugalija",
  "PR": "Puerto Rikas",
  "QA": "Kataras",
  "RE": "Reunionas",
  "RO": "Rumunija",
  "RU": "Rusija",
  "RW": "Ruanda",
  "BL": "Šv. Bartolomėjaus sala",
  "SH": "Šventoji Elena",
  "KN": "Sent Kitsas ir Nevis",
  "LC": "Sent Lusija",
  "MF": "Šv. Martyno sala",
  "PM": "Sen Pjeras ir Mikelonas",
  "VC": "Sent Vinsentas ir Grenadinai",
  "WS": "Samoa",
  "SM": "San Marinas",
  "ST": "San Tomė ir Prinsipė",
  "SA": "Saudo Arabija",
  "SN": "Senegalas",
  "RS": "Serbija",
  "SC": "Seišeliai",
  "SL": "Siera Leonė",
  "SG": "Singapūras",
  "SX": "Sint Martenas",
  "SK": "Slovakija",
  "SI": "Slovėnija",
  "SB": "Saliamono salos",
  "SO": "Somalis",
  "ZA": "Pietų Afrikos Respublika",
  "GS": "Pietų Džordžija ir Pietų Sandvičo salos",
  "KR": "Pietų Korėja",
  "SS": "Pietų Sudanas",
  "ES": "Ispanija",
  "LK": "Šri Lanka",
  "SD": "Sudanas",
  "SR": "Surinamas",
  "SJ": "Svalbardas",
  "SZ": "Svazilandas",
  "SE": "Švedija",
  "CH": "Šveicarija",
  "SY": "Sirija",
  "TW": "Taivanas",
  "TJ": "Tadžikija",
  "TZ": "Tanzanija",
  "TH": "Tailandas",
  "TG": "Togas",
  "TK": "Tokelau",
  "TO": "Tonga",
  "TT": "Trinidadas ir Tobagas",
  "TN": "Tunisas",
  "TR": "Turkija",
  "TM": "Turkmėnija",
  "TC": "Terksas ir Kaikosas",
  "TV": "Tuvalu",
  "VI": "Mergelių salos (JAV)",
  "UG": "Uganda",
  "UA": "Ukraina",
  "AE": "Jungtiniai Arabų Emyratai",
  "GB": "Jungtinė Karalystė",
  "US": "JAV",
  "UY": "Urugvajus",
  "UZ": "Uzbekija",
  "VU": "Vanuatu",
  "VA": "Vatikanas",
  "VE": "Venesuela",
  "VN": "Vietnamas",
  "WF": "Volisas ir Futuna",
  "WW": "Visame pasaulyje",
  "EH": "Vakarų Sachara",
  "YE": "Jemenas",
  "ZM": "Zambija",
  "ZW": "Zimbabvė",
  "search": "Paieška",
};
