Map<String, String> nl = {
  "AF": "Afghanistan",
  "AX": "Åland",
  "AL": "Albanië",
  "DZ": "Algerije",
  "AS": "Amerikaans-Samoa",
  "AD": "Andorra",
  "AO": "Angola",
  "AI": "Anguilla",
  "AG": "Antigua en Barbuda",
  "AR": "Argentinië",
  "AM": "Armenië",
  "AW": "Aruba",
  "AC": "Ascension",
  "AU": "Australië",
  "AT": "Oostenrijk",
  "AZ": "Azerbeidzjan",
  "BS": "Bahama's",
  "BH": "Bahrein",
  "BD": "Bangladesh",
  "BB": "Barbados",
  "BY": "Wit-Rusland",
  "BE": "België",
  "BZ": "Belize",
  "BJ": "Benin",
  "BM": "Bermuda",
  "BT": "Bhutan",
  "BO": "Bolivië",
  "BA": "Bosnië-Herzegovina",
  "BW": "Botswana",
  "BR": "Brazilië",
  "IO": "Brits Indische oceaan",
  "VG": "Maagdeneilanden, Britse",
  "BN": "Brunei Darussalam",
  "BG": "Bulgarije",
  "BF": "Burkina Faso",
  "BI": "Burundi",
  "KH": "Cambodja",
  "CM": "Kameroen",
  "CA": "Canada",
  "CV": "Kaapverdië",
  "BQ": "Bonaire, Sint Eustatius en Saba",
  "KY": "Kaaimaneilanden",
  "CF": "Centraal-Afrikaanse Republiek",
  "TD": "Tsjaad",
  "CL": "Chili",
  "CN": "China",
  "CX": "Christmaseiland",
  "CC": "Cocoseilanden",
  "CO": "Colombia",
  "KM": "Comoren",
  "CD": "Congo, Democratische Republiek",
  "CG": "Congo, Volksrepubliek",
  "CK": "Cookeilanden",
  "CR": "Costa Rica",
  "CI": "Ivoorkust",
  "HR": "Kroatië",
  "CU": "Cuba",
  "CW": "Curaçao",
  "CY": "Cyprus",
  "CZ": "Tsjechië",
  "DK": "Denemarken",
  "DJ": "Djibouti",
  "DM": "Dominica",
  "DO": "Dominicaanse Republiek",
  "TL": "Timor Leste",
  "EC": "Ecuador",
  "EG": "Egypte",
  "SV": "El Salvador",
  "GQ": "Equatoriaal-Guinea",
  "ER": "Eritrea",
  "EE": "Estland",
  "ET": "Ethiopië",
  "FK": "Falklandeilanden",
  "FO": "Faeröer",
  "FJ": "Fiji",
  "FI": "Finland",
  "FR": "Frankrijk",
  "GF": "Frans-Guyana",
  "PF": "Frans-Polynesië",
  "GA": "Gabon",
  "GM": "Gambia",
  "GE": "Georgië",
  "DE": "Duitsland",
  "GH": "Ghana",
  "GI": "Gibraltar",
  "GR": "Griekenland",
  "GL": "Groenland",
  "GD": "Grenada",
  "GP": "Guadeloupe",
  "GU": "Guam",
  "GT": "Guatemala",
  "GG": "Guernsey",
  "GN": "Guinea",
  "GW": "Guinee-Bissau",
  "GY": "Guyana",
  "HT": "Haïti",
  "HM": "Heard en McDonaldeilanden",
  "HN": "Honduras",
  "HK": "Hong Kong",
  "HU": "Hongarije",
  "IS": "IJsland",
  "IN": "India",
  "ID": "Indonesië",
  "IR": "Iran",
  "IQ": "Irak",
  "IE": "Ierland",
  "IM": "Man Eiland",
  "IL": "Israël",
  "IT": "Italië",
  "JM": "Jamaica",
  "JP": "Japan",
  "JE": "Jersey",
  "JO": "Jordanië",
  "KZ": "Kazachstan",
  "KE": "Kenia",
  "KI": "Kiribati",
  "XK": "Kosovo",
  "KW": "Koeweit",
  "KG": "Kirgizstan",
  "LA": "Laos",
  "LV": "Letland",
  "LB": "Libanon",
  "LS": "Lesotho",
  "LR": "Liberia",
  "LY": "Libië",
  "LI": "Liechtenstein",
  "LT": "Litouwen",
  "LU": "Luxemburg",
  "MO": "Macao",
  "MK": "Noord-Macedonië",
  "MG": "Madagaskar",
  "MW": "Malawi",
  "MY": "Maleisië",
  "MV": "Maldiven",
  "ML": "Mali",
  "MT": "Malta",
  "MH": "Marshalleilanden",
  "MQ": "Martinique",
  "MR": "Mauritanië",
  "MU": "Mauritius",
  "YT": "Mayotte",
  "MX": "Mexico",
  "FM": "Micronesië, Federale Staten",
  "MD": "Moldavië",
  "MC": "Monaco",
  "MN": "Mongolië",
  "ME": "Montenegro",
  "MS": "Montserrat",
  "MA": "Marokko",
  "MZ": "Mozambique",
  "MM": "Myanmar",
  "NA": "Namibië",
  "NR": "Nauru",
  "NP": "Nepal",
  "NL": "Nederland",
  "NC": "Nieuw-Caledonië",
  "NZ": "Nieuw-Zeeland",
  "NI": "Nicaragua",
  "NE": "Niger",
  "NG": "Nigeria",
  "NU": "Niue",
  "NF": "Norfolk",
  "KP": "Noord-Korea",
  "MP": "Noordelijke Marianen",
  "NO": "Noorwegen",
  "OM": "Oman",
  "PK": "Pakistan",
  "PW": "Palau",
  "PS": "Palestina",
  "PA": "Panama",
  "PG": "Papoea-Nieuw-Guinea",
  "PY": "Paraguay",
  "PE": "Peru",
  "PH": "Filipijnen",
  "PL": "Polen",
  "PT": "Portugal",
  "PR": "Puerto Rico",
  "QA": "Qatar",
  "RE": "Réunion",
  "RO": "Roemenië",
  "RU": "Rusland",
  "RW": "Rwanda",
  "BL": "Saint Barthélemy",
  "SH": "Sint-Helena",
  "KN": "Saint Kitts en Nevis",
  "LC": "Saint Lucia",
  "MF": "Sint-Maarten (Frans deel)",
  "PM": "Saint-Pierre en Miquelon",
  "VC": "Saint Vincent en de Grenadines",
  "WS": "Samoa",
  "SM": "San Marino",
  "ST": "São Tomé en Principe",
  "SA": "Saudi-Arabië",
  "SN": "Senegal",
  "RS": "Servië",
  "SC": "Seychellen",
  "SL": "Sierra Leone",
  "SG": "Singapore",
  "SX": "Sint Maarten",
  "SK": "Slowakije",
  "SI": "Slovenië",
  "SB": "Salomonseilanden",
  "SO": "Somalië",
  "ZA": "Zuid-Afrika",
  "GS": "Zuid-Georgia en de Zuidelijke Sandwicheilanden",
  "KR": "Zuid-Korea",
  "SS": "Zuid-Soedan",
  "ES": "Spanje",
  "LK": "Sri Lanka",
  "SD": "Soedan",
  "SR": "Suriname",
  "SJ": "Spitsbergen en Jan Mayen",
  "SZ": "Ngwane, Koninkrijk Eswatini",
  "SE": "Zweden",
  "CH": "Zwitserland",
  "SY": "Syrië",
  "TW": "Taiwan",
  "TJ": "Tadzjikistan",
  "TZ": "Tanzania",
  "TH": "Thailand",
  "TG": "Togo",
  "TK": "Tokelau",
  "TO": "Tonga",
  "TT": "Trinidad en Tobago",
  "TN": "Tunesië",
  "TR": "Turkije",
  "TM": "Turkmenistan",
  "TC": "Turks- en Caicoseilanden",
  "TV": "Tuvalu",
  "VI": "Maagdeneilanden, Amerikaanse",
  "UG": "Oeganda",
  "UA": "Oekraïne",
  "AE": "Verenigde Arabische Emiraten",
  "GB": "Groot-Brittannië",
  "US": "Verenigde Staten van Amerika",
  "UY": "Uruguay",
  "UZ": "Oezbekistan",
  "VU": "Vanuatu",
  "VA": "Heilige Stoel",
  "VE": "Venezuela",
  "VN": "Vietnam",
  "WF": "Wallis en Futuna",
  "WW": "Wereldwijd",
  "EH": "Westelijke Sahara",
  "YE": "Jemen",
  "ZM": "Zambia",
  "ZW": "Zimbabwe",
  "search": "Zoeken",
};
