Map<String, String> nn = {
  "AF": "Afghanistan",
  "AX": "Åland",
  "AL": "Albania",
  "DZ": "Algerie",
  "AS": "Amerikansk Samoa",
  "AD": "Andorra",
  "AO": "Angola",
  "AI": "Anguilla",
  "AG": "Antigua og Barbuda",
  "AR": "Argentina",
  "AM": "Armenia",
  "AW": "Aruba",
  "AC": "Ascension",
  "AU": "Australia",
  "AT": "Austerrike",
  "AZ": "Aserbajdsjan",
  "BS": "Bahamas",
  "BH": "Bahrain",
  "BD": "Bangladesh",
  "BB": "Barbados",
  "BY": "Kviterussland",
  "BE": "Belgia",
  "BZ": "Belize",
  "BJ": "Benin",
  "BM": "Bermuda",
  "BT": "Bhutan",
  "BO": "Bolivia",
  "BA": "Bosnia-Hercegovina",
  "BW": "Botswana",
  "BR": "Brasil",
  "IO": "Det britiske territoriet i Indiahavet",
  "VG": "Dei britiske Jomfruøyane",
  "BN": "Brunei",
  "BG": "Bulgaria",
  "BF": "Burkina Faso",
  "BI": "Burundi",
  "KH": "Kambodsja",
  "CM": "Kamerun",
  "CA": "Canada",
  "CV": "Kapp Verde",
  "BQ": "Karibisk Nederland",
  "KY": "Caymanøyane",
  "CF": "Den sentralafrikanske republikken",
  "TD": "Tsjad",
  "CL": "Chile",
  "CN": "Kina",
  "CX": "Christmasøya",
  "CC": "Kokosøyane",
  "CO": "Colombia",
  "KM": "Komorane",
  "CD": "Den demokratiske republikken Kongo",
  "CG": "Republikken Kongo",
  "CK": "Cookøyane",
  "CR": "Costa Rica",
  "CI": "Elfenbeinskysten",
  "HR": "Kroatia",
  "CU": "Cuba",
  "CW": "Curaçao",
  "CY": "Kypros",
  "CZ": "Tsjekkia",
  "DK": "Danmark",
  "DJ": "Djibouti",
  "DM": "Dominica",
  "DO": "Den dominikanske republikken",
  "TL": "Aust-Timor",
  "EC": "Ecuador",
  "EG": "Egypt",
  "SV": "El Salvador",
  "GQ": "Ekvatorial-Guinea",
  "ER": "Eritrea",
  "EE": "Estland",
  "ET": "Etiopia",
  "FK": "Falklandsøyane",
  "FO": "Færøyane",
  "FJ": "Fiji",
  "FI": "Finland",
  "FR": "Frankrike",
  "GF": "Fransk Guyana",
  "PF": "Fransk Polynesia",
  "GA": "Gabon",
  "GM": "Gambia",
  "GE": "Georgia",
  "DE": "Tyskland",
  "GH": "Ghana",
  "GI": "Gibraltar",
  "GR": "Hellas",
  "GL": "Grønland",
  "GD": "Grenada",
  "GP": "Guadeloupe",
  "GU": "Guam",
  "GT": "Guatemala",
  "GG": "Guernsey",
  "GN": "Guinea-Conakry",
  "GW": "Guinea-Bissau",
  "GY": "Guyana",
  "HT": "Haiti",
  "HM": "Heard- og McDonaldøyane",
  "HN": "Honduras",
  "HK": "Hongkong",
  "HU": "Ungarn",
  "IS": "Island",
  "IN": "India",
  "ID": "Indonesia",
  "IR": "Iran",
  "IQ": "Irak",
  "IE": "Irland",
  "IM": "Man",
  "IL": "Israel",
  "IT": "Italia",
  "JM": "Jamaica",
  "JP": "Japan",
  "JE": "Jersey",
  "JO": "Jordan",
  "KZ": "Kasakhstan",
  "KE": "Kenya",
  "KI": "Kiribati",
  "XK": "Kosovo",
  "KW": "Kuwait",
  "KG": "Kirgisistan",
  "LA": "Laos",
  "LV": "Latvia",
  "LB": "Libanon",
  "LS": "Lesotho",
  "LR": "Liberia",
  "LY": "Libya",
  "LI": "Liechtenstein",
  "LT": "Litauen",
  "LU": "Luxemburg",
  "MO": "Macao",
  "MK": "Nord-Makedonia",
  "MG": "Madagaskar",
  "MW": "Malawi",
  "MY": "Malaysia",
  "MV": "Maldivane",
  "ML": "Mali",
  "MT": "Malta",
  "MH": "Marshalløyane",
  "MQ": "Martinique",
  "MR": "Mauritania",
  "MU": "Mauritius",
  "YT": "Mayotte",
  "MX": "Mexico",
  "FM": "Mikronesiaføderasjonen",
  "MD": "Moldova",
  "MC": "Monaco",
  "MN": "Mongolia",
  "ME": "Montenegro",
  "MS": "Montserrat",
  "MA": "Marokko",
  "MZ": "Mosambik",
  "MM": "Myanmar [Burma]",
  "NA": "Namibia",
  "NR": "Nauru",
  "NP": "Nepal",
  "NL": "Nederland",
  "NC": "Ny-Caledonia",
  "NZ": "New Zealand",
  "NI": "Nicaragua",
  "NE": "Niger",
  "NG": "Nigeria",
  "NU": "Niue",
  "NF": "Norfolkøya",
  "KP": "Nord-Korea",
  "MP": "Nord-Marianane",
  "NO": "Noreg",
  "OM": "Oman",
  "PK": "Pakistan",
  "PW": "Palau",
  "PS": "Palestina",
  "PA": "Panama",
  "PG": "Papua Ny-Guinea",
  "PY": "Paraguay",
  "PE": "Peru",
  "PH": "Filippinane",
  "PL": "Polen",
  "PT": "Portugal",
  "PR": "Puerto Rico",
  "QA": "Qatar",
  "RE": "Réunion",
  "RO": "Romania",
  "RU": "Russland",
  "RW": "Rwanda",
  "BL": "Saint-Barthélemy",
  "SH": "St. Helena",
  "KN": "St. Kitts og Nevis",
  "LC": "St. Lucia",
  "MF": "Saint-Martin",
  "PM": "Saint-Pierre og Miquelon",
  "VC": "St. Vincent og Grenadinane",
  "WS": "Samoa",
  "SM": "San Marino",
  "ST": "São Tomé og Príncipe",
  "SA": "Saudi-Arabia",
  "SN": "Senegal",
  "RS": "Serbia",
  "SC": "Seychellane",
  "SL": "Sierra Leone",
  "SG": "Singapore",
  "SX": "Sint Maarten",
  "SK": "Slovakia",
  "SI": "Slovenia",
  "SB": "Salomonøyane",
  "SO": "Somalia",
  "ZA": "Sør-Afrika",
  "GS": "Sør-Georgia og Sør-Sandwichøyane",
  "KR": "Sør-Korea",
  "SS": "Sør-Sudan",
  "ES": "Spania",
  "LK": "Sri Lanka",
  "SD": "Sudan",
  "SR": "Surinam",
  "SJ": "Svalbard og Jan Mayen",
  "SZ": "Eswatini",
  "SE": "Sverige",
  "CH": "Sveits",
  "SY": "Syria",
  "TW": "Taiwan",
  "TJ": "Tadsjikistan",
  "TZ": "Tanzania",
  "TH": "Thailand",
  "TG": "Togo",
  "TK": "Tokelau",
  "TO": "Tonga",
  "TT": "Trinidad og Tobago",
  "TN": "Tunisia",
  "TR": "Tyrkia",
  "TM": "Turkmenistan",
  "TC": "Turks- og Caicosøyane",
  "TV": "Tuvalu",
  "VI": "De amerikanske jomfruøyane",
  "UG": "Uganda",
  "UA": "Ukraina",
  "AE": "Dei sameinte arabiske emirata",
  "GB": "Storbritannia",
  "US": "USA",
  "UY": "Uruguay",
  "UZ": "Usbekistan",
  "VU": "Vanuatu",
  "VA": "Vatikanstaten",
  "VE": "Venezuela",
  "VN": "Vietnam",
  "WF": "Wallis og Futuna",
  "WW": "Verdensomspennende",
  "EH": "Vest-Sahara",
  "YE": "Jemen",
  "ZM": "Zambia",
  "ZW": "Zimbabwe",
  "search": "Søk",
};
