Map<String, String> pl = {
  "AF": "Afganistan",
  "AX": "Wyspy Alandzkie",
  "AL": "Albania",
  "DZ": "Algieria",
  "AS": "Samoa Amerykańskie",
  "AD": "Andora",
  "AO": "Angola",
  "AI": "Anguilla",
  "AG": "Antigua i Barbuda",
  "AR": "Argentyna",
  "AM": "Armenia",
  "AW": "Aruba",
  "AC": "Wyspa Wniebowstąpienia",
  "AU": "Australia",
  "AT": "Austria",
  "AZ": "Azerbejdżan",
  "BS": "Bahamy",
  "BH": "Bahrajn",
  "BD": "Bangladesz",
  "BB": "Barbados",
  "BY": "Białoruś",
  "BE": "Belgia",
  "BZ": "Belize",
  "BJ": "Benin",
  "BM": "Bermudy",
  "BT": "Bhutan",
  "BO": "Boliwia",
  "BA": "Bośnia i Hercegowina",
  "BW": "Botswana",
  "BR": "Brazylia",
  "IO": "Brytyjskie Terytorium Oceanu Indyjskiego",
  "VG": "Brytyjskie Wyspy Dziewiczes",
  "BN": "Brunei",
  "BG": "Bułgaria",
  "BF": "Burkina Faso",
  "BI": "Burundi",
  "KH": "Kambodża",
  "CM": "Kamerun",
  "CA": "Kanada",
  "CV": "Wyspy Zielonego Przylądka",
  "BQ": "Karaiby Holandia",
  "KY": "Kajmany",
  "CF": "Republika Środkowoafrykańska",
  "TD": "Czad",
  "CL": "Chile",
  "CN": "Chiny",
  "CX": "Wyspa Bożego Narodzenia",
  "CC": "Wyspy Kokosowe [Keelinga]",
  "CO": "Kolumbia",
  "KM": "Komory",
  "CD": "Demokratyczna Republika Konga",
  "CG": "Republika Konga",
  "CK": "Wyspy Cooka",
  "CR": "Kostaryka",
  "CI": "Wybrzeże Kości Słoniowej",
  "HR": "Chorwacja",
  "CU": "Kuba",
  "CW": "Curaçao",
  "CY": "Cypr",
  "CZ": "Republika Czeska",
  "DK": "Dania",
  "DJ": "Dżibuti",
  "DM": "Dominika",
  "DO": "Republika Dominikany",
  "TL": "Wschodni Timor",
  "EC": "Ekwador",
  "EG": "Egipt",
  "SV": "Salwador",
  "GQ": "Gwinea Równikowa",
  "ER": "Erytrea",
  "EE": "Estonia",
  "ET": "Etiopia",
  "FK": "Falklandy [Islas Malvinas]",
  "FO": "Wyspy Owcze",
  "FJ": "Fidżi",
  "FI": "Finlandia",
  "FR": "Francja",
  "GF": "Gujana Francuska",
  "PF": "Polinezja Francuska",
  "GA": "Gabon",
  "GM": "Gambia",
  "GE": "Gruzja",
  "DE": "Niemcy",
  "GH": "Ghana",
  "GI": "Gibraltar",
  "GR": "Grecja",
  "GL": "Grenlandia",
  "GD": "Grenada",
  "GP": "Gwadelupa",
  "GU": "Guam",
  "GT": "Gwatemala",
  "GG": "Guernsey",
  "GN": "Gwinea Konakry",
  "GW": "Gwinea Bissau",
  "GY": "Gujana",
  "HT": "Haiti",
  "HM": "Wyspy Heard i McDonalda",
  "HN": "Honduras",
  "HK": "Hongkong",
  "HU": "Węgry",
  "IS": "Islandia",
  "IN": "Indie",
  "ID": "Indonezja",
  "IR": "Iran",
  "IQ": "Irak",
  "IE": "Irlandia",
  "IM": "Wyspa Man",
  "IL": "Izrael",
  "IT": "Włochy",
  "JM": "Jamajka",
  "JP": "Japonia",
  "JE": "Jersey",
  "JO": "Jordania",
  "KZ": "Kazakhstan",
  "KE": "Kenia",
  "KI": "Kiribati",
  "XK": "Kosowo",
  "KW": "Kuwejt",
  "KG": "Kirgistan",
  "LA": "Laos",
  "LV": "Łotwa",
  "LB": "Liban",
  "LS": "Lesotho",
  "LR": "Liberia",
  "LY": "Libia",
  "LI": "Liechtenstein",
  "LT": "Litwa",
  "LU": "Luksemburg",
  "MO": "Makau",
  "MK": "Macedonia",
  "MG": "Madagaskar",
  "MW": "Malawi",
  "MY": "Malezja",
  "MV": "Malediwy",
  "ML": "Mali",
  "MT": "Malta",
  "MH": "Wyspy Marshalla",
  "MQ": "Martynika",
  "MR": "Mauretania",
  "MU": "Mauritius",
  "YT": "Majotta",
  "MX": "Meksyk",
  "FM": "Mikronezja",
  "MD": "Moldova",
  "MC": "Monako",
  "MN": "Mongolia",
  "ME": "Czarnogóra",
  "MS": "Montserrat",
  "MA": "Maroko",
  "MZ": "Mozambik",
  "MM": "Myanmar [Burma]",
  "NA": "Namibia",
  "NR": "Nauru",
  "NP": "Nepal",
  "NL": "Holandia",
  "NC": "Nowa Kaledonia",
  "NZ": "Nowa Zelandia",
  "NI": "Nikaragua",
  "NE": "Niger",
  "NG": "Nigeria",
  "NU": "Niue",
  "NF": "Wyspa Norfolk",
  "KP": "Korea Północna",
  "MP": "Mariany Północne",
  "NO": "Norwegia",
  "OM": "Oman",
  "PK": "Pakistan",
  "PW": "Palau",
  "PS": "Terytoria Palestyńskie",
  "PA": "Panama",
  "PG": "Papua Nowa Gwinea",
  "PY": "Paragwaj",
  "PE": "Peru",
  "PH": "Filipiny",
  "PL": "Polska",
  "PT": "Portugalia",
  "PR": "Portoryko",
  "QA": "Katar",
  "RE": "Reunion",
  "RO": "Rumunia",
  "RU": "Rosja",
  "RW": "Rwanda",
  "BL": "Saint Barthélemy",
  "SH": "Święta Helena",
  "KN": "Św. Kitts",
  "LC": "Św. Lucia",
  "MF": "Święty Marcin",
  "PM": "Saint-Pierre i Miquelon",
  "VC": "Św. Wincentego",
  "WS": "Samoa",
  "SM": "San Marino",
  "ST": "Wyspy Świętego Tomasza i Książęca",
  "SA": "Arabia Saudyjska",
  "SN": "Senegal",
  "RS": "Serbia",
  "SC": "Seszele",
  "SL": "Sierra Leone",
  "SG": "Singapur",
  "SX": "Sint Maarten",
  "SK": "Słowacja",
  "SI": "Słowenia",
  "SB": "Wyspy Salomona",
  "SO": "Somali",
  "ZA": "Afryka Południowa",
  "GS": "Georgia Południowa i Sandwich Południowy",
  "KR": "Korea Południowa",
  "SS": "Południowy Sudan",
  "ES": "Hiszpania",
  "LK": "Sri Lanka",
  "SD": "Sudan",
  "SR": "Surinam",
  "SJ": "Svalbard i Jan Mayen",
  "SZ": "Suazi",
  "SE": "Szwecja",
  "CH": "Szwajcaria",
  "SY": "Syria",
  "TW": "Tajwan",
  "TJ": "Tadżykistan",
  "TZ": "Tanzania",
  "TH": "Tajlandia",
  "TG": "Togo",
  "TK": "Tokelau",
  "TO": "Tonga",
  "TT": "Trynidad i Tobago",
  "TN": "Tunezja",
  "TR": "Turcja",
  "TM": "Turkmenia",
  "TC": "Wyspy Turks i Caicos",
  "TV": "Tuvalu",
  "VI": "Wyspy Dziewicze Stanów Zjednoczonych",
  "UG": "Uganda",
  "UA": "Ukraina",
  "AE": "Zjednoczone Emiraty Arabskie",
  "GB": "Zjednoczone Królestwo",
  "US": "Stany Zjednoczone",
  "UY": "Urugwaj",
  "UZ": "Uzbekistan",
  "VU": "Vanuatu",
  "VA": "Watykan",
  "VE": "Wenezuela",
  "VN": "Wietnam",
  "WF": "Wallis i Futuna",
  "WW": "Na Całym Świecie",
  "EH": "Sahara Zachodnia",
  "YE": "Jemen",
  "ZM": "Zambia",
  "ZW": "Zimbabwe",
  "search": "Szukaj",
};
